### ISSUE TITLE
FUNCTIONALITY ISSUE (GROUP - 04)  Total time spend in the campus is not calculated

### ISSUE THREAD

**Issue by Chess-shrutiDubey** [IITGN-CS431/project-cns#100]
**As according to the instruction** (-T Gives the total time spent in the campus by an employee or guest, over the whole history of the log. If the employee or guest is currently in the campus, include the time spent so far in this visit as well as total time spent in prior visits. Output is an integer on a single line. If the specified employee or guest does not appear in the campus log, then nothing is printed. If an employee or guest enters at time 1 and leaves at time 10, the total time is 9 seconds), **Iam unable to calculate the total time.**

![time](https://github.com/user-attachments/assets/3f1369d7-d25c-49c1-a8a2-0c65ac258b8c)

**Comment by bichhawat** [comment]
This is optional; if they have not implemented this, this will not be a bug

**Comment by bichhawat** [comment]
I am going to close this as you have already reported the max. limit
