### ISSUE TITLE
FUNCTIONALITY ISSUE (GROUP - 02) : Person state inconsistent across different logs

### ISSUE THREAD

**Issue by VenkatReddybathuni** [IITGN-CS431/project-cns#108]
Giving the following set of instructions through a batch file:

![image](https://github.com/user-attachments/assets/36907ba3-d356-4b83-a688-e6d80a766f62)

and then reading the state of rooms:

![image](https://github.com/user-attachments/assets/fbcbe647-69d7-44f0-83c5-bb0d4f382dcc)

This is wrong because when a person enters the campus from log2 then he is on campus. But he was again allowed to enter the campus through log1.

Ideally there should have been an error message when we try to enter using the second log.

**Comment by bichhawat** [comment]
Adding to different logs are okay as they are independent logs. The issues need to be within the same log.

**Comment by VenkatReddybathuni** [comment]
But @bichhawat sir this will cause a lot of inconsistencies for example consider this case where I entered these following instructions 

![image](https://github.com/user-attachments/assets/0231c85c-e9cd-4748-abb7-a7ed847c762f)


Then upon reading the states the output came out to be as follows:

![image](https://github.com/user-attachments/assets/d1478a57-018e-4b12-8b50-c92d14e54935)

This is clearly giving inconsitent position of the person because when the person leaves the campus then he should not be read as present on campus in any log.

So I think the persons should have a consistent position in all the logs.

**Comment by bichhawat** [comment]
I do not think we had a requirement of consistencies across logs. If that is untrue, please let me know. 
A log is maintained at the high-level so two different logs can have similar values as long as they do not cause problems for the other. I am unable to come up with an example where this could be an issue. More pointers to me here would help.
