### ISSUE TITLE
Functionality Issue: No response from server with load testing (Group8)

### ISSUE THREAD

**Issue by Quantizate** [IITGN-CS431/project-cns#109]
Please find the procedure of attack in the video link attached. [link](https://drive.google.com/file/d/1kRbj5smVV1HNgWYb5UqyDtv51E1yk3t4/view?usp=sharing)

**Comment by cpatel321** [comment]
This was a nice demonstration, but it looks like there might be some issues with memory management. Could you confirm if there's enough RAM available to keep the server running under load? Also, it seems that at the end of the test, the ./server process wasn't verified to be running before launching the client. This could mean that the server was killed by the OS due to high load. Could you double-check these aspects in your setup?

**Comment by Quantizate** [comment]
@cpatel321 please check the docker memory and cpu usage, that is shown below in the docker application 
Linking the screenshots. I have been running this on a mac M1 with 16 Gb ram out of which 8 Gbs is available to docker and an 8 core cpu, I think there are no OS or memory management issues. Looking forward to your response. 
![Screenshot 2024-10-26 at 11 01 07 PM](https://github.com/user-attachments/assets/8817f799-decf-4198-9639-4b8c0f26d68d)
![Screenshot 2024-10-26 at 11 01 18 PM](https://github.com/user-attachments/assets/692e5c80-1c5c-4cd7-8a0f-7ef6005e653c)
![Screenshot 2024-10-26 at 11 01 18 PM](https://github.com/user-attachments/assets/18be6bd8-3bd0-41a8-b40a-dad88b71da74)
Ps: the first screenshot is directly taken from the video

**Comment by Quantizate** [comment]
I have also made sure to check this multiple times, and this is a reproducible one.

**Comment by bichhawat** [comment]
@Quantizate Please provide more details of the bug, and share the test file that you used for the bug so that the group can replicate and fix it.

**Comment by cpatel321** [comment]
In my opinion, no function error was shown in server log, so it may be because of the 1 second delay implemented between each command execution or probably because of closing of server. Anyways @Quantizate please share the test file for us to test it locally as soon possible.

**Comment by cpatel321** [comment]
I have executed the given benchmark tool on our application, and for reference, here is the [video of my manual testing](https://drive.google.com/file/d/1aHEfJ_mz7DjSwVYo_ygHd5Nzod0UHMfv/view?usp=sharing).

A few observations: under a very high load, any application can potentially crash, and that is essentially the nature of a DoS attack. If our server does crash in such cases, a straightforward restart will ensure there is no data loss. Therefore, I believe this should not be classified as a bug.

Furthermore, the techniques typically used to mitigate the chances of a DoS attack are complex, resource-intensive, and may not be feasible or worthwhile to implement here. Adding such services could introduce unnecessary overhead without effectively solving the issue at hand.

@bichhawat sir, based on these points, I think this issue should be marked as "won't fix." 
Regardless of how many thread limitations we impose, there will always be an open port vulnerable to such high traffic, making complete protection against DoS infeasible in this context.

**Comment by Quantizate** [comment]
Nice try, whatever helps you sleep at night.

**Comment by corrosive4354** [comment]
During the load test, use tools such as htop or Docker's monitoring tool to monitor the server's CPU and memory usage. Make sure the server process is active during the test.

In addition, there are too many compatibility issues between Docker and Mac on the Internet. You can replace Docker with [Servbay](https://servbay.com) to deploy the environment. Servbay is more professional on Mac and supports one-click deployment.
