### ISSUE TITLE
Security Bug (Group 2): All log files can be tampered

### ISSUE THREAD

**Issue by Kishan-Ved** [IITGN-CS431/project-cns#110]
There is no functionality for client and server interactions on 2 separate machines (one client and another server). Hence, all log files are on the same machine. These are encrypted, but can be tampered.

Follow this:
Run: `./setup pass log1` 

This creates a new file named log1, with some encrypted text. 

![image](https://github.com/user-attachments/assets/f6956559-4797-4b01-89b1-77a34477f39c)

Type some gibberish into it.

![image](https://github.com/user-attachments/assets/a1b830a2-a79e-447c-ba23-d8d987eea49a)

Now, run: `./logappend -T 1 -K pass -A -E Alice log1`. It shows authentication failed.

![image](https://github.com/user-attachments/assets/29640e6f-d705-4273-bdd1-cca6d0103c75)

**NOTE**: If the log files were on a server (a separate machine), and the client was another machine, then this bug would be invalid. But I don't see any client and server based implementation. Your app runs on only one machine.

**Comment by Chess-shrutiDubey** [comment]
It is not mentioned anywhere that client-server implementation should be used. A similar issue #4 was raised, which is closed now. Please kindly refer to that one. The point of adding anything gibberish in the log file is that, first of all, log file entries are entirely stored in encrypted form. Nobody can read without a password. Secondly, even if you add anything gibberish into the log file directly, it now becomes corrupted, and the log read function will not be performed in this

**Comment by Kishan-Ved** [comment]
Ok, consider this:
- Make a log file, add a log. This is what you get.
![image](https://github.com/user-attachments/assets/2262dfa1-ac70-4cfe-b069-cd5aa4b8f438)

- Copy line 2
![image](https://github.com/user-attachments/assets/1ea3ad00-9db3-48b4-8a5d-93f1ecb87acd)

- Now, perform logread
![image](https://github.com/user-attachments/assets/3edc8d09-9e27-4a96-8c9d-f5633cee04e1)

**Comment by Kishan-Ved** [comment]
The point that I am trying to express is that your application allows me to write directly to the log file, even without knowing the key for that log. As in the above example, I put another Alice into the campus without the key.

My issue differs from #4 which says that log files are on the same machine. I agree that is not a problem. However, I can **tamper** these log files without the key. That is the actual problem.

**Comment by bichhawat** [comment]
This is an integrity violation as pointed out in the last comment.

**Comment by naveeeeeeeeeen** [comment]
**BUG RESOLVED**
**On client side you only need the client.py file( make sure the server IP and Port no. are correct)
Running on client side and executing commands:
Here the client side is on Shruti's laptop:**
![CNS1](https://github.com/user-attachments/assets/76fbb70e-2603-4e3e-91c8-53e6d321d2e6)

**On server side, server receives commands from client, executes them and sends back the appropriate response:
The server side is running on Naveen's laptop:**
![Screenshot from 2024-10-29 20-26-03](https://github.com/user-attachments/assets/7cbb7a81-3725-408a-bf99-c0e22492667b)

**All the log file are stored on server machine, no tampering can be done by clients now.**
