### ISSUE TITLE
Functional Bug (Group 4)

### ISSUE THREAD

**Issue by Vraj2811** [IITGN-CS431/project-cns#122]
It doesn't properly update the log files when the user enters the room 0. I
When it exits from room 0, it exits the campus

![image](https://github.com/user-attachments/assets/4f6ef0b1-a56c-44de-995c-65935c093419)

**Comment by VenkatReddybathuni** [comment]
This bug was fixed and queued in pull request before the bug was even reported.

**Comment by bichhawat** [comment]
@VenkatReddybathuni can you please provide the bug number? thanks.
