### ISSUE TITLE
Functionality Bug (Group-12): Issue with long names

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#124]
While handling long names, the message received from the server gets corrupted. Server side shows correct info, but client side shows wrong information. Full name of the person is not shown. This also hampers the information of the next employees/guests whose name are not at all shown at the client side while logread.
The below are client system responses:
![image](https://github.com/user-attachments/assets/4da8f5fb-5bca-4c77-957b-8640e72640ba)
![image](https://github.com/user-attachments/assets/5b49375a-a129-4964-9300-0a106d5a43ba)

The below is server response for the same:
![image](https://github.com/user-attachments/assets/ef3f8a8f-40f1-470c-a6fb-46c84c2b46f8)

**Comment by shubham-agrawal04** [comment]
Different from the issue #87  This arises after that bug is fixed.

**Comment by bichhawat** [comment]
Please fix this by tomorrow as requested for no penalties.

**Comment by chakrie1489** [comment]
Fixed.
