### ISSUE TITLE
Functionality Issue [Group 1] : Exit Signals Not Handled Properly

### ISSUE THREAD

**Issue by AshStorm17** [IITGN-CS431/project-cns#126]
![Screenshot 2024-10-27 102451](https://github.com/user-attachments/assets/8f1cf56f-3bf3-4861-9bdf-c301cfee8ce9)

I Exited the bank with Ctrl+Z and got some unusual behaviour.
It seems that the bank still occupies the port 8080, and thus I cannot rerun it.

![Screenshot 2024-10-27 102503](https://github.com/user-attachments/assets/d78ebe7b-3485-40a2-8c5c-5183c84bb9da)
The atm when run after closing the bank with Ctrl+Z enters a state of waiting infinitely.

Firstly, the exit signal should be handled.
Secondly, since the port can be preoccupied in other cases, hardcoding it is not an ideal way.

**Comment by bichhawat** [comment]
Ctl + Z is actually only pausing the program so the bank program is still active (in the background) and has not closed. Ctl + C is the one that terminates the program. Handling signals would be a little too much expectations at this point when we have not discussed OS.
I agree that hardcoding is not ideal but it should be okay here as the server is the only one that is accessing this.
