### ISSUE TITLE
Functionality Bug(Group 9): Application Accepts Invalid Deposit of 0.00 Instead of Displaying Error [# 128]

### ISSUE THREAD

**Issue by PrateekG93** [IITGN-CS431/project-cns#128]
The application allows a deposit of 0.00, which contradicts the expected behavior as per the rule stating that the deposit amount must be greater than 0.00.

![PHOTO-2024-10-27-16-13-03](https://github.com/user-attachments/assets/5bc90345-b73e-4cbf-95d5-ef447a1ba9dd)

The application should reject a deposit of 0.00 and display an error message indicating that the deposit amount must be greater than 0.00.

**Comment by ushasree-3** [comment]
#174 #175 #176
