### ISSUE TITLE
Functionality Bug (Group 9) : Application Hang on Invalid Account Name Input [#129]

### ISSUE THREAD

**Issue by arpan004** [IITGN-CS431/project-cns#129]
When providing an account name enclosed in single (') or double (") quotes as input, the program hangs, requiring manual termination using Ctrl+C. Instead of showing an error message for an invalid account name, the program fails to respond.

![WhatsApp Image 2024-10-27 at 16 11 26_0c985278](https://github.com/user-attachments/assets/c6cbb1ad-a9e3-40c9-9a1d-8a3f171209a5)

**Expected Behavior:**  it should give “Invalid account name”

**Comment by bichhawat** [comment]
It is actually waiting for the string to terminate as they may be reading this as a string. This should be okay unless when the quotes are closed, this is still stuck.
