### ISSUE TITLE
Functionality Bug (Group 9) : Incorrect input Parsing when Card File Name is Omitted [#130]

### ISSUE THREAD

**Issue by arpan004** [IITGN-CS431/project-cns#130]
If the user leaves the card file name empty while executing the ATM command, the program incorrectly treats the next parameter (-i) as the card file name. As a result, the IP address parameter is misinterpreted, leading to unexpected behavior instead of showing an error message stating that the card file name cannot be blank.

![WhatsApp Image 2024-10-27 at 16 30 46_20059b03](https://github.com/user-attachments/assets/76d2a435-fe44-47dd-a12a-73eebb826b63)

**Comment by ushasree-3** [comment]
#174 #175 #176
