### ISSUE TITLE
Functionality Bug (Group 9):  Runtime Error on Attempting to Withdraw from a Non-Existent Account [#131]

### ISSUE THREAD

**Issue by PrateekG93** [IITGN-CS431/project-cns#131]
When attempting to withdraw from an account that has not been created, the program throws a runtime error. Specifically, it fails to open a file for reading and terminates the process unexpectedly.

![Bug 2](https://github.com/user-attachments/assets/cdfdb261-3b00-457d-b403-d16824ff820e)

**Expected Behavior:**
The program should check if the account exists before attempting any operations and should provide a user-friendly error message if the account does not exist.

**Comment by ushasree-3** [comment]
#174 #175 #176
