### ISSUE TITLE
Functionality Bug (Group 9): Inaccurate Balance Display [#132]

### ISSUE THREAD

**Issue by PrateekG93** [IITGN-CS431/project-cns#132]
When performing calculations involving monetary values, the program shows unexpected behavior by displaying balances with excessive decimal places and also gives the incorrect account balance. Like in this case subtracting 0.01 from 10.01 results in a balance of 169.99000000000001 instead of the expected 10.00.

![Bug 3](https://github.com/user-attachments/assets/c18b07b9-ca2a-4d74-b16f-3fad54b2da39)

**Comment by ushasree-3** [comment]
![img2](https://github.com/user-attachments/assets/71bc26cf-6807-481c-bc29-3d4dec4cadcc)

I have tested the code on my laptop, and it is working properly. The balance calculations return the expected values without any discrepancies. Subtracting 0.01 from 10.01 correctly results in 10.00. Please check your environment or input values if you're experiencing issues.

**Comment by ushasree-3** [comment]
PR no. : #174 #175 #176
