### ISSUE TITLE
Runtime Error (Group 9) : Error on Invalid Account Name for Certain Inputs [#133]

### ISSUE THREAD

**Issue by arpan004** [IITGN-CS431/project-cns#133]
While testing the ATM system, a discrepancy was observed between expected error handling and actual program behavior. When an invalid account name containing special characters such as "@@" is provided, the system correctly throws the "Invalid account name" error. However, when the account name "my" is used, the program throws a std::runtime_error and terminates with the message:

![WhatsApp Image 2024-10-27 at 16 53 32_5ca2b433](https://github.com/user-attachments/assets/fc5b1bea-5756-4b04-b980-cab2e584803a)

This inconsistency suggests that the input "my" triggers an unexpected runtime error, which should ideally be handled gracefully and return the same "Invalid account name" message.

**Comment by ushasree-3** [comment]
PR no.: #174 #175 #176
