### ISSUE TITLE
Functionality Bug (Group 7): Deposit Accepts Zero, Ignoring Minimum Requirement [#134]

### ISSUE THREAD

**Issue by PrateekG93** [IITGN-CS431/project-cns#134]
The ATM client allows a deposit of 0.00 into an account, which contradicts the specification [link](https://github.com/IITGN-CS431/project-cns/blob/main/atm/atm.md) that states the deposit amount must be greater than 0.00.

![image](https://github.com/user-attachments/assets/1f93a982-8792-4f3f-9aa1-64a084087387)

The system should reject any deposit amount of 0.00 and should display an error message indicating that the deposit amount must be greater than 0.00.

**Comment by RuchitJagodara** [comment]
Fixed !
