### ISSUE TITLE
Functionality Bug (Group 2) : Non Numeric Values like "", +, \ being accepted as Room Number and Time Stamp

### ISSUE THREAD

**Issue by aditya-me13** [IITGN-CS431/project-cns#136]
According to the description: 
<img width="1533" alt="Screenshot 2024-10-27 at 8 12 19 PM" src="https://github.com/user-attachments/assets/bc30e00c-dcdf-4853-9a8c-a5465b498ac6">

But the program accepts characters like ```""```, ```+```, ```\``` and ``` ``` in the room id reference 
Please refer to the following commands:

<img width="1148" alt="Screenshot 2024-10-27 at 8 08 58 PM" src="https://github.com/user-attachments/assets/f86a5f03-2612-4a16-a52c-9c8433074601">

<img width="1208" alt="Screenshot 2024-10-27 at 8 18 03 PM" src="https://github.com/user-attachments/assets/ee586839-690c-4760-b96c-daee28a97e93">

<img width="1195" alt="Screenshot 2024-10-27 at 8 18 38 PM" src="https://github.com/user-attachments/assets/a11df9a3-6daa-4bcc-b410-c48879008e70">

<img width="1194" alt="Screenshot 2024-10-27 at 8 11 05 PM" src="https://github.com/user-attachments/assets/cab05721-ead7-42df-bd13-d6d3a68cab93">

<img width="1375" alt="Screenshot 2024-10-27 at 8 20 33 PM" src="https://github.com/user-attachments/assets/ba8649bf-2dc1-42d1-bc57-1be64e599ad9">

**Comment by aditya-me13** [comment]
The same is true for Time Stamp as well. I don't know if this should be reported as a separate bug (as the same change would fix both the bugs)

Refer to the following commands:

<img width="1172" alt="Screenshot 2024-10-27 at 8 35 06 PM" src="https://github.com/user-attachments/assets/8c696703-9aa2-4892-838e-b04ec93b1a7d">

<img width="1218" alt="Screenshot 2024-10-27 at 8 33 44 PM" src="https://github.com/user-attachments/assets/d174907c-fab8-4344-aaec-67dc872ae2ea">

<img width="1141" alt="Screenshot 2024-10-27 at 8 34 03 PM" src="https://github.com/user-attachments/assets/4b90111b-c0a8-46b8-bad2-1988f732c876">

**Comment by naveeeeeeeeeen** [comment]
RESOLVED
![Screenshot from 2024-11-05 19-00-32](https://github.com/user-attachments/assets/94e9ced1-ef78-4248-babc-75438c70e390)
