### ISSUE TITLE
Functionality Bug (Group 1) : Allowing Zero Amount Transactions

### ISSUE THREAD

**Issue by Chhavigoyal02** [IITGN-CS431/project-cns#137]
The deposit and withdraw functions currently allow transactions with an amount of 0, which is against the specification that requires transaction amounts to be greater than 0.

![image](https://github.com/user-attachments/assets/7ad60e18-188c-4de3-97d8-9f1a2ea0a148)
 Validation should be added to ensure that the amount is strictly positive before proceeding with the transaction.

**Comment by Jiya-desai** [comment]
Hello @Chhavigoyal02, the transaction amount need not be strictly positive. Kindly check the specifications - it clearly says that all values from 0.00 to 4294967295.99 **inclusively** are valid inputs.

![image](https://github.com/user-attachments/assets/94cecee2-d56b-40ce-8097-e0aead95ca5b)

**Comment by Chhavigoyal02** [comment]
In the 2nd and 3rd points, it is clearly stated that the deposit and withdrawal amounts must be greater than 0.00.

![image](https://github.com/user-attachments/assets/1e598556-2184-44ff-be42-4495e4c6eaa2)

**Comment by bichhawat** [comment]
Please fix this as per the spec.
