### ISSUE TITLE
Functionality Bug (Group 1) : JSON Format Missing for Transaction Outputs

### ISSUE THREAD

**Issue by ishikajain212** [IITGN-CS431/project-cns#139]
The project does not output transaction details (deposit, withdrawal, and balance check) in JSON format, as specified.
 
![WhatsApp Image 2024-10-27 at 20 35 56_24e105f5](https://github.com/user-attachments/assets/93122a48-83d6-47c3-8a11-5e2c355fb855)

Update transaction outputs to follow the specified JSON format.

**Comment by nishishah05** [comment]
Hello @ishikajain212. Professor Bichhawat mentioned that we might use an alternate interface for a better user experience; hence, (in accordance with the user factor design principle), we chose this one.

**Comment by bichhawat** [comment]
This is okay as far as the output is processed and shown correctly.
