### ISSUE TITLE
Functionality Bug (Group 7) -  Improper Server Exit Causes Port Binding Issue

### ISSUE THREAD

**Issue by Chhavigoyal02** [IITGN-CS431/project-cns#141]
When the server is terminated using Ctrl + Z, it doesn’t release the port properly, leading to a "port already in use" error upon restarting. This is likely due to the server process remaining active in the background. 

![image](https://github.com/user-attachments/assets/d7c2796b-9a39-4be7-ac7a-c6ccda324cac)
Proper signal handling and graceful shutdown are needed to ensure the port is freed upon exit.

**Comment by bichhawat** [comment]
Ctl Z is only pausing the programs so it should be okay.
