### ISSUE TITLE
Functionality Bug (Group 5) : Valid name are not being accepted as account names 

### ISSUE THREAD

**Issue by Pratham-Sharda** [IITGN-CS431/project-cns#142]
Here when I am making an account with my name  as "." and ".." it is giving me invalid, but it should accept this as they are valid names according to Sir's specifications 

![WhatsApp Image 2024-10-28 at 01 44 13_66a740fe](https://github.com/user-attachments/assets/56df902e-76b3-49ed-a6db-a304ac838424)

![WhatsApp Image 2024-10-28 at 01 48 07_d5246910](https://github.com/user-attachments/assets/62e6d736-6803-4f87-92e1-3617e0168d86)

**Comment by AshStorm17** [comment]
I think you have not pulled the latest codebase.
This bug was resolved in PR #29
