### ISSUE TITLE
Function Bug (Group-5): Valid card and bank file name not accepted

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#143]
Below is the input I tried:
![image](https://github.com/user-attachments/assets/fb7c15a2-163b-4527-95a1-5ae3e1f4ae62)

According to the requirements mentioned, it should have been accepted, it is valid input
![image](https://github.com/user-attachments/assets/f0dbaecc-f855-44b4-b6ba-3a43c47e1201)
![image](https://github.com/user-attachments/assets/af1f0aa3-6045-42ac-89d5-7b1639925dfe)

**Comment by shubham-agrawal04** [comment]
Same issue with the bank authentication file name
![image](https://github.com/user-attachments/assets/7d4c3793-0d26-47f2-af74-f3549ae0608f)

**Comment by AshStorm17** [comment]
bank auth files need to have the extension .auth, and card files need to have the extension .card.
This is not a bug but a convention we adopted on purpose to make things more streamlined and organised in the working environment.

**Comment by shubham-agrawal04** [comment]
Did you specify this somewhere in your design document or readme?

**Comment by shubham-agrawal04** [comment]
Without proper specification of the above, this should be considered a bug because initial requirements ask it to be valid.

**Comment by AshStorm17** [comment]
I dont think having an extension is a bug 🙂.
![{9BEC3658-26C0-40DC-84D3-734E51D20C6B}](https://github.com/user-attachments/assets/c45992aa-52d8-46a0-9b35-228b261681cb)
![{A4E93C64-7E1C-4A67-B4F5-9832BEE9AD10}](https://github.com/user-attachments/assets/3fad4ac6-0147-4319-9f23-d69f53a3db42)
For your reference the requirements mentioned in the problem statement.
I don't think it is then an assumption that we had made. It was just our understanding of the statement.

**Comment by shubham-agrawal04** [comment]
That refers to the default value, however it states on the index.md the actual valid inputs. As long as you don't explicitly state that such and such are the assumptions or conventions we apply (for better organisation, like you mentioned earlier), it should be considered as a valid input that is not getting accepted.
@bichhawat Sir, please verify

**Comment by bichhawat** [comment]
The default thing is a little orthogonal to the discussion here: it means that if nothing is specified, this is how you create it and use it.
@AshStorm17 If you require a .card/.auth extension, please mention it in README

**Comment by aayush8991** [comment]
Sir, we have implemented the code according to our understanding. In this case, we required the user to enter the file name with .card extension. We will update this in the readme but we do not feel that this should be considered as a bug.

**Comment by bichhawat** [comment]
@aayush8991 I agree that it may not be a serious issue but requires users to understand how to pass inputs to the program. The user may refer to the initial spec or your READMEs. If either of them does not contain this detail, it is a functionality issue as far the user is concerned. The fixing of README is not a big task and should be doable soon in which case there would not be any penalty on your side.

**Comment by AshStorm17** [comment]
The Readme was updated in PR #214
