### ISSUE TITLE
Functionality Bug - Group 5 - Valid account name not being accepted

### ISSUE THREAD

**Issue by Jiya-desai** [IITGN-CS431/project-cns#144]
I entered a 116-characters-long account name - which should be valid according to the specifications - but it gave me the following error:
![image](https://github.com/user-attachments/assets/8b2144e7-6b22-4689-afd2-6639325d2bb7)

**Comment by AshStorm17** [comment]
Thanks for pointing out.
We defined the .SQL file to store less characters during testing and forgot to change it as per the requirements.
Will make the adjustments.
