### ISSUE TITLE
Functionality Bug (Group 5): Invalid Transaction amount being accepted

### ISSUE THREAD

**Issue by Pratham-Sharda** [IITGN-CS431/project-cns#145]
When i am making an account with amount 5000000000 as the initial amount it is being accepted .(Which should not be accepted according to Sir's specifications)

![WhatsApp Image 2024-10-28 at 02 04 40_b6fd6bdd](https://github.com/user-attachments/assets/28f5cbab-313c-40f1-b6d4-ddb7406f5ddd)

**Comment by bichhawat** [comment]
Why is this number not acceptable? Can you please point me to the line in the spec?

Also, this is not my spec but the application's spec :).

**Comment by bichhawat** [comment]
Oh, got it now. Command line inputs are upper bounded by 4294967295.99. Please fix this accordingly.
