### ISSUE TITLE
Functionality Bug (Group 10) : Non Numeric Values like "", +, space being accepted as Room Number and Time Stamp

### ISSUE THREAD

**Issue by aditya-me13** [IITGN-CS431/project-cns#146]
According to the description:
<img width="1533" alt="380505938-bc30e00c-dcdf-4853-9a8c-a5465b498ac6" src="https://github.com/user-attachments/assets/fa34f6aa-6136-47d2-aa50-d80ceb3fb0bb">

But the program accepts characters like ```""```, ```+``` and ``` ```  in the room id reference
Please refer to the following commands:
<img width="1006" alt="Screenshot 2024-10-28 at 2 37 53 AM" src="https://github.com/user-attachments/assets/54bbc220-42f1-46b1-b557-fce561d3b500">
<img width="999" alt="Screenshot 2024-10-28 at 2 38 11 AM" src="https://github.com/user-attachments/assets/c83baa03-525a-42f7-9839-93e2cc6f5ef4">

Ideally time stamp and Room Number must not accept characters like ```""``` or ```+```.
Again I don't know if these should be reported as separate bugs.

**Comment by rovin99** [comment]
<img width="557" alt="Screenshot 2024-11-01 at 5 04 03 PM" src="https://github.com/user-attachments/assets/3918e054-4c1a-47cf-aa00-f02d444c8e30">
Fixed with PR 239
