### ISSUE TITLE
Bug (Group 7) : Unnecessary Card File Creation Vulnerability

### ISSUE THREAD

**Issue by arpan004** [IITGN-CS431/project-cns#147]
The ATM system allows for the creation of new accounts by generating a unique card file. During account creation, if an account with the specified name already exists, the server returns an error (Account already exists for name <AccountName>). However, even though the account creation fails, the system still generates a card file with the specified name. This results in the creation of "useless" card files, which are not linked to any valid account on the server.

![WhatsApp Image 2024-10-27 at 19 37 16_fd8f7ce8](https://github.com/user-attachments/assets/26d74b65-1ae1-4430-80aa-6b6066b87c85)

**Expected Behavior:** 
If account creation fails due to a name conflict or any other reason, the ATM system should not generate or save the card file. The process should halt without any changes to the file system.

**Comment by bichhawat** [comment]
While generating a file with that name is not possibly a bug, being able to use that later may be a bug. Please check if that can happen.
