### ISSUE TITLE
Functionality Bug (Group 7): Application Hangs on Invalid Account Name Input 

### ISSUE THREAD

**Issue by PrateekG93** [IITGN-CS431/project-cns#148]
When an account name is provided with single (') or double (") quotes, the application becomes unresponsive and requires manual termination with Ctrl+C. Instead of displaying an error message indicating "Invalid account name," the program fails to respond as expected.

![image](https://github.com/user-attachments/assets/fface20d-3b64-4dd8-acc7-b4395f839fa2)

**Expected Behavior:**
The application should display “Invalid account name” for improperly formatted input.

**Comment by bichhawat** [comment]
This should be okay, as discussed, because of UNIX conventions. If it does not fail after providing a closing string, then there could be an issue. If so, please open a new issue with relevant details
