### ISSUE TITLE
FunctionalityIssue (Group 10): Logread and Logread accepting garbage values in the command

### ISSUE THREAD

**Issue by aditya-me13** [IITGN-CS431/project-cns#149]
The `logread` command runs without errors for two log files at once if the log files share the same secret. 

In the first three commands below, notice that the log files `log1` and `log2` have the same secret, allowing the `logread` command in the third instance to execute successfully. Ideally, it should only accept one log file to read at a time.

However, an error occurs if two log files specified in the `logread` command have different secrets. In this case, `log3` and `log4` have secrets `secret3` and `secret4`, respectively. Therefore, command 6 throws an error when attempting to read both files simultaneously.

<img width="870" alt="Screenshot 2024-10-28 at 3 09 51 AM" src="https://github.com/user-attachments/assets/e49224c0-7a85-43d9-8f3d-bd8b4ac82285">

This appears to be a functionality issue,however the ability to access two log files at once could lead to security vulnerabilities. Since I have access to all the log files (I can see their names but not their contents, refer image below)
<img width="173" alt="Screenshot 2024-10-28 at 3 24 35 AM" src="https://github.com/user-attachments/assets/710385d5-de30-420f-883c-617ff17cb884">
I could theoretically perform a brute force attack to check if the password of my log file matches anyone else's. While this may seem impractical on a smaller scale, the potential for collisions (where two log files share the same secret) increases significantly with larger datasets. 

I am still uncertain whether this constitutes a security issue or merely a functionality issue. @bichhawat  sir, could you please clarify this?

**Comment by aditya-me13** [comment]
This is actually true for ```logappend``` as well. Here the log file ```log5``` was not created before. However the below shown command lead to updation in ```log4``` and a creation of new log file ```log5``` with the same secret, without throwing any error.

<img width="912" alt="Screenshot 2024-10-28 at 3 29 33 AM" src="https://github.com/user-attachments/assets/395fdd3c-ab38-41a5-9e8d-0361ddb35e58">

**Comment by bichhawat** [comment]
Are the entries the same, too (or copied/similar) in the two cases? This could then be a security bug.
While having the same password is okay (we are allowing brute forcing), parsing logs as you have shown is not fine and needs to be fixed. There needs to be consistency in how they are handled. I am not sure which log is being accessed, or is it both the logs?

**Comment by aditya-me13** [comment]
Sorry, it was by bad. It is just a functionality issue. User can add any space separated text in the ```./logread``` and ```./logappend``` commands and only the first or last value will be considered. Here is the example

<img width="1269" alt="Screenshot 2024-10-28 at 6 13 28 PM" src="https://github.com/user-attachments/assets/1eefcda9-48f7-4328-aef2-20b6d810c932">

The actual value it is taking as parameter is highlighted below. Rest of the information is just garbage value, which ideally shouldn't be allowed.

![Screenshot 2024-10-28 at 6 13 28 PM png-1](https://github.com/user-attachments/assets/ffb58873-a324-4d59-aa3a-e74011cc87d4)
