### ISSUE TITLE
Functionality Bug(Group-12) Invalid time calculated

### ISSUE THREAD

**Issue by Chess-shrutiDubey** [IITGN-CS431/project-cns#15]
Here the alice entered in campus at timestamp 1 and she is there till time 12. So time calculated should be 12-1 =11 .But the time shown for any entry like this is showing 0.
![2](https://github.com/user-attachments/assets/e1158a6b-ffc5-4186-b08a-7eebe65f54c5)

**Comment by chakrie1489** [comment]
Fixed
