### ISSUE TITLE
Functional Bug (Group-1): Invalid card and bank auth file names accepted

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#150]
PFA my test for both card-file name(Password) and bank auth-file name
1. Invalid Characters accepted in Card-file name
![image](https://github.com/user-attachments/assets/2421e4ea-67f7-4ebf-87ae-1ea6a79f40a8)
2. Invalid Characters accepted in Bank Auth-file name
![image](https://github.com/user-attachments/assets/ea6b6ceb-d904-4780-83c4-b024f6e70fe3)
3. Invalid length accepted in Bank Auth-file name (test-case is 240 chars long)
![image](https://github.com/user-attachments/assets/f8e25562-dbd9-43ed-88fe-2d7e76215767)

As per requirements, these should not be accepted.
![image](https://github.com/user-attachments/assets/338f108f-ddd6-4dee-a07d-83dd12933496)

**Comment by Jiya-desai** [comment]
In our model, each registered user is assigned a unique username and password. We have assumed that each valid user is in possession of this information, and they can choose to share it with anyone. No explicit 'files' are being created, **so the password for each user doesn't have to be validated by the file naming convention, as you have interpreted.** 
Even the creation of the auth file doesn't need to be specified as a parameter in the command for running the bank or the atm. The auth files already exist with valid names; only their contents are being modified during the runs.

From our readme:
![image](https://github.com/user-attachments/assets/3d8d2fc1-07d7-453b-bb6e-4a485e8a2d2e)

**Comment by shubham-agrawal04** [comment]
Okay, thanks for the clarification.
However I still don't understand the point regarding the authentication files and why they are not required to follow the naming convention.

**Comment by shubham-agrawal04** [comment]
It wasn't asked to hardcode the file name, users should be able to give input the auth file names, in the initial specifications. 
However, even considering this, shouldn't an extra unnecessary command raise some error, instead of completely disregarding it?
@bichhawat Sir, let us know your opinion.

**Comment by Jiya-desai** [comment]
Deciding the names of the auth files is not a user functionality, nor does it pose a security concern. The auth files on both the client and server sides must contain the same verification code to authenticate the connection. From our readme:

![image](https://github.com/user-attachments/assets/be144ad5-db3d-40bd-8144-ce0cea19e914)

The assumption about there being a secure way through which the mutual auth key is communicated between the bank and the atm is valid, as discussed with Sir and our TAs. We have further explained in our system setup guide how the auth file authentication works. Both the bank and atm programs should be started using ./bank and ./atm, respectively.

As for why the extra arguments don't raise an error, I believe it pertains to the operating system and how it handles command-line parameters - in this case, extra arguments are being discarded. I suppose we can modify the code to handle extra arguments, but is it necessary? The commands ./bank and ./atm are sufficient to run the programs, as mentioned, and any extra arguments are being ignored, and do not interfere with the working of either programs.

**Comment by bichhawat** [comment]
As their design and interface is a little different, it seems okay to allow this.
