### ISSUE TITLE
Functionality Bug(Group-12) Inconsistence Issue

### ISSUE THREAD

**Issue by Chess-shrutiDubey** [IITGN-CS431/project-cns#16]
When anyone entered in a negative room  named -1, first of all it is not showed in log read although it is successfully added to that room. Secondly anyone in this room can change room without leaving it which is an issue.
![3 (2)](https://github.com/user-attachments/assets/490b5666-cd4d-40ea-a757-233d8cfe0f62)
![3 (3)](https://github.com/user-attachments/assets/a1fea6e1-7621-473a-a57b-bc1e66ca818f)

**Comment by chakrie1489** [comment]
Fixed.
