### ISSUE TITLE
Security Bug(Group -11): There is no authentication to verify if the atm is actual or malicious user.

### ISSUE THREAD

**Issue by Pratham-Sharda** [IITGN-CS431/project-cns#162]
In the code of Group -11, I can connect to a bank without needing to authenticate the atm.
The atm just uses public key to connect and assuming that public key is available to everyone (assumption is made as no clarification has been given in the readme regarding the public key, which is generally available to all).
Thus it is required to verify the atm to ensure that no malicious person can become an atm.

**Comment by bichhawat** [comment]
Can you provide few more details by showing some transactions assuming an atm is rogue?

**Comment by Pratham-Sharda** [comment]
![image](https://github.com/user-attachments/assets/0ef7e124-1575-47c4-9c9d-3b9e27d447ec)
![image](https://github.com/user-attachments/assets/6e29bbf2-4db5-4230-b23e-8c672968a974)

So here i can run atm from anywhere with just public key thus making a malicious user to easily become atm

**Comment by Chhavigoyal02** [comment]
We have resolved this issue in PR #231.
