### ISSUE TITLE
GROUP 11 - PORT MISCONFIGURATION

### ISSUE THREAD

**Issue by heerkubadia** [IITGN-CS431/project-cns#163]
The application server is intended to run on port 8080;
`#define SERVER_PORT 8080`

 however, it is accessible on an unintended port (61186). 
`bank_f    45467 heerkubadia    3u  IPv4 0x640896be53aad2c1      0t0    TCP *:61186 (LISTEN)`

This misconfiguration poses several security risks, including unintended exposure of sensitive services, potential unauthorized access, and vulnerabilities to port scanning attacks. Additionally, it can lead to confusion among clients regarding which port to connect to.

**Comment by Chhavigoyal02** [comment]
Did you modify the port number in the source code?
If yes, it should function correctly on any publicly accessible port specified in the code file.
If not, please provide more details, as I checked on our system and found that the code is only accessible on the defined port, not on any other.

**Comment by heerkubadia** [comment]
No I didnt change anything in the source code. As I wasn’t able to connect I checked where the executable was running.

**Comment by krupaphd24** [comment]
> Did you modify the port number in the source code? If yes, it should function correctly on any publicly accessible port specified in the code file. If not, please provide more details, as I checked on our system and found that the code is only accessible on the defined port, not on any other.

Yes, and in rare case if only 8080 is occupied it can use other ones randomly. Still if you aren't able to connect with server "at all", we can update it for other means.

**Comment by heerkubadia** [comment]
I did check if 8080 was occupied but it wasn’t.

**Comment by krupaphd24** [comment]
@heerkubadia it is not a bug in your repo/ project. Then it shouldn't apply here also.

**Comment by heerkubadia** [comment]
My issue was not that the port is hardcoded. Bank wasn’t running on the hardcoded port even when the port was available.
