### ISSUE TITLE
Functional Bug(group-11):Using database as auth file

### ISSUE THREAD

**Issue by Pratham-Sharda** [IITGN-CS431/project-cns#165]
Using the database as auth file is a bug, as whenever the bank closes, the database gets erased, and a new database has to be generated every time we start the bank server. Thus once the bank closes the database is lost forever as next time we run the bank new database has to be generated .

**Comment by Chhavigoyal02** [comment]
Our auth file is functioning correctly. We've tested it on two different devices (one with a VM and one without), and we're able to log in even after restarting the server.

![WhatsApp Image 2024-10-29 at 00 48 20_9959dc0a](https://github.com/user-attachments/assets/d49fcb73-e13f-4c72-adb9-7a7438f7d043)

![WhatsApp Image 2024-10-29 at 00 49 45_a01b5ffd](https://github.com/user-attachments/assets/412c213e-c71d-4e39-8554-d8dec9af877c)

 Please verify on your end as well.

**Comment by bichhawat** [comment]
Reopen the issue if it is not working, with more details.
