### ISSUE TITLE
GROUP 7 - Functionality issue - Invalid deposit amount getting accepted.

### ISSUE THREAD

**Issue by lavanya2504** [IITGN-CS431/project-cns#168]
According to the spec, numeric inputs cannot have leading zeroes. But when I deposited an amount of 0053.09, it got accepted. (Initially, the balance was zero)

```
lavanya04@DESKTOP-3IU7VB2:/mnt/c/Users/Lavanya/Downloads/project-cns-main/project-cns-main/project-submissions/group-7$ ./atm1 -s bank.auth -c lavanya8.card -a lavanya8 -d 0053.09
Connecting with the Bank Server...
Response from the Bank Server:
Money deposited succesfully and your updated balance is 53.09
```

**Comment by RuchitJagodara** [comment]
I reviewed the deposit functionality requirements and noticed there is no mention of disallowing leading zeroes. Additionally, our function appears to work correctly even with leading zeros.

**Comment by lavanya2504** [comment]
![image](https://github.com/user-attachments/assets/24175c3a-b600-4ba7-a90e-8824317083e9)

Please refer to the above screenshot.

**Comment by lavanya2504** [comment]
@bichhawat sir, Can you please check the above screenshot and reopen the issue?
