### ISSUE TITLE
GROUP 7 - SECURITY ISSUE - DENIAL OF SERVICE 

### ISSUE THREAD

**Issue by heerkubadia** [IITGN-CS431/project-cns#169]
![WhatsApp Image 2024-10-28 at 23 51 36](https://github.com/user-attachments/assets/8fbb1f13-4c3c-4d8c-b3ba-245b034d3bdd)

![WhatsApp Image 2024-10-28 at 23 53 16](https://github.com/user-attachments/assets/dc5fb477-b970-4c34-a3bb-1b28390afacb)

As observed in the provided screenshots, the server's responses ceased after a certain number of requests without encountering any crash or timeout errors. Instead, the responses were simply paused, as indicated by the timestamps in the bottom right corner of the images. This behavior demonstrates that the Denial of Service attack was successful, effectively overwhelming the server and halting its ability to process incoming requests.

**Comment by RuchitJagodara** [comment]
Can you please provide the script you used for the attack so that we can recreate the issue?

**Comment by RuchitJagodara** [comment]
Fixed through commit 
 b1632af
