### ISSUE TITLE
Security Bug (Group- 12): Log entries stored as plaintext, Passwords stored as plaintext in a file named 'keys.csv'. 

### ISSUE THREAD

**Issue by naveeeeeeeeeen** [IITGN-CS431/project-cns#17]
![Screenshot from 2024-10-24 14-36-10](https://github.com/user-attachments/assets/e341d90a-6dd3-43d2-8bd5-19e2323d3179)
![Screenshot from 2024-10-24 14-35-53](https://github.com/user-attachments/assets/90b0ae44-b1d2-490b-a9d0-8cc4f3870588)
![Screenshot from 2024-10-24 14-35-44](https://github.com/user-attachments/assets/d72afaff-2be1-40fc-bd1b-89979e76c4b1)
**Major Security flaw as all the password files and log files  are available to be read and altered by anyone. 
Entries are not encrypted and rather stored as plaintext.
No major security features implemented.**

**Comment by bichhawat** [comment]
Any attempt to learn something about the log’s contents, or to change them, without the use of the logread and logappend and the proper token should be disallowed. You cannot store the logs in plaintext

**Comment by chakrie1489** [comment]
Fixed. Encrypted the contents of key.csv and log files.
