### ISSUE TITLE
functionality bug (group-3) :  Data Loss on Bank Server Restart

### ISSUE THREAD

**Issue by ishikajain212** [IITGN-CS431/project-cns#170]
When the bank server is stopped, all data is lost, including account information. Upon restarting the bank server, there is no data backup, so any previously created accounts are erased, requiring users to recreate accounts and preventing re-login to prior sessions. 

on bank side :-
![WhatsApp Image 2024-10-28 at 20 34 53_ca917659](https://github.com/user-attachments/assets/881cb64c-91b0-4f5d-a914-a1787e02239d)

on atm side :-
![WhatsApp Image 2024-10-28 at 20 34 54_5c5f76e0](https://github.com/user-attachments/assets/b56118af-3df3-4265-8341-7ea37aed7867)

**Comment by Quantizate** [comment]
Actually since we have dockerized the whole server process, we are not using persistent data storage. 

@bichhawat sir we have one way to takle this that is to introduce persistence through docker volumes but the problem is data path might differ based on the os. Any suggestions for the same?

**Comment by YYashraj** [comment]
The current implementation assumes that each run of the bank server operates with a unique accounts database. Restarting the server means serving a new and different bank instance, effectively creating a fresh database and losing previously stored data. This design was aimed at keeping each server session independent, allowing for testing of multiple user interactions through the ATM client.
However, we also understand the need for a more persistent setup to maintain account continuity. Thank you @ishikajain212 for raising this concern.

**Comment by bichhawat** [comment]
Please identify this in your README as a design decision. You should also try to provide a code outside of docker so that users who want to install it can do so.
