### ISSUE TITLE
Security Bug (Group 6) Issues in logappend

### ISSUE THREAD

**Issue by Vraj2811** [IITGN-CS431/project-cns#172]
If I use logappend in the log file, the logappend gets corrupted. 
I was not able to directly use logappend in log file so created a symbolic link between logappend and log.txt 

![image](https://github.com/user-attachments/assets/d650ab86-e8f5-428b-ace5-485d327ab4e8)

Finally, the logappend file does not work

**Comment by Shr-Agr** [comment]
The issue has now been resolved.

The logappend executable file cannot be corrupted by creating a symbolic link.
If the filepath/filename does not correspond to a regular file path (either relative or absolute), then the program will exit without changing the logappend executable, as shown below:

![Screenshot 2024-10-29 222927](https://github.com/user-attachments/assets/b64a42dc-45be-47a3-9906-77221d74b3bb)
