### ISSUE TITLE
Group 9- Multiple iterations leads to incorrect formatting

### ISSUE THREAD

**Issue by nishishah05** [IITGN-CS431/project-cns#173]
Upon running multiple iterations of withdrawal, deposits and check balances, the balance amount is formatted incorrectly with 10+ digits after the decimal points.
![Screenshot 2024-10-29 003850](https://github.com/user-attachments/assets/48b3e552-0f87-405f-82f3-da037ff3b14f)

**Comment by bichhawat** [comment]
Can you elaborate on multiple iterations? Does the issue happen after you run it multiple times or is it every time you run it from the beginning.

**Comment by ushasree-3** [comment]
PR : #174 #175 #176
