### ISSUE TITLE
Minor Bug(Group-11)[Could Be A Potential Security Bug]: Unnecessary usage of Card_id and Account_No

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#177]
Upon analysis of the source code, I found that the account number and the card id, generated during a successful registration of a user, are generated using a random number number generator, and hence they lose their uniqueness upon being generated randomly, multiple users can have same card id and account number.
![image](https://github.com/user-attachments/assets/b19e03e7-53e2-4503-9fb0-610619a3fd3e)
![image](https://github.com/user-attachments/assets/180462c9-a282-4760-b51e-3dd5f5121e72)

While this does not really affect the current implementation of the system, it may be a potential security bug in future if it's considered unique, (because in reality, account numbers are unique for each account holder). 
Also, at the current level of implementation, do we really require an account number and a card-id? because each username is required to be unique as an initial specification, in which case these are just unnecessary and serve no purpose.
![image](https://github.com/user-attachments/assets/f4d28c5c-9268-4084-abb2-1763a00c3213)

**Comment by shubham-agrawal04** [comment]
I also pondered whether these may be added as an additional security to the account, in case even if the password is known, the card_id and account number asked during login serve as 2nd and 3rd layer of security. But even in that case, it's only a 10^10 and 10^16 possible combinations brute force which is really not computationally heavy these days.

**Comment by krupaphd24** [comment]
That's true for any real world account numbers and card id too. I don't think purpose or intention of the project was to create perfect random numbers or series driven numbers for id purposes. If not generated, then again it could become a bug that what if card and password etc lost.

**Comment by shubham-agrawal04** [comment]
But then what purpose do they serve here? As i see it, the system would have completely sound and foolproof even if these weren't added, just have the username and password for logging in.

**Comment by krupaphd24** [comment]
Hello , I guess you are mentioning 4th bug to the same repo and it's not advised as part of project instructions. Kindly look into it.

> Every individual can report up to a maximum of 3 bugs (both security and functionality) per target group and a total of 8 bugs. The test case should clearly identify the inputs provided, the output obtained and the expected output, and the files/functionality targeted as part of the test-case. 

>

**Comment by bichhawat** [comment]
@shubham-agrawal04 It is a great suggestion and if the feature itself is leading to a bug, then it may be worth reporting. If not, the designs are as per the groups' understanding and we may not want to discuss that here (due to the shortage of time).
