### ISSUE TITLE
Functionality Bug(Group-9): Invalid Bank Auth Filenames accepted

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#179]
The specifications clearly state that uppercase letters are not allowed in the file names. Still, the bank auth filename SHUBHAM.auth is created and bank server starts, instead of raising an error.
![image](https://github.com/user-attachments/assets/2f182280-b57e-40f9-b4ee-8608d4d142de)

For reference:
![image](https://github.com/user-attachments/assets/70736855-2c6c-4aec-917e-7bf0c5e14575)

**Comment by ushasree-3** [comment]
#192 #193
