### ISSUE TITLE
Minor Functionality Issue (Group 1) : Port Hardcoded in bank file

### ISSUE THREAD

**Issue by AshStorm17** [IITGN-CS431/project-cns#18]
![{1B940C7E-A1FB-408D-92DF-D367EE6EF72C}](https://github.com/user-attachments/assets/a6d00225-6ebc-440d-a274-cd5806e00cc5)
The port 8080 has been hardcoded. No other ports available to connect.

**Comment by bichhawat** [comment]
I think this is okay as long as this for the server
