### ISSUE TITLE
Functional Bug(Group-9): Creation of Auth file for invalid port number

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#180]
When entering an invalid port number, the server first creates a new auth file, (either with default name or with specified name), and then raises an error about invalid port. However, it should raise error before creating any such files, as this then renders the filename to not be able to be reused. 
![image](https://github.com/user-attachments/assets/e864a4f7-486e-45c8-bf2f-823591ba2f98)
![image](https://github.com/user-attachments/assets/254a5ee2-afcf-48ed-b408-7181a789cbb2)

**Comment by ushasree-3** [comment]
#192 #193
