### ISSUE TITLE
Functional Bug(Group-9): Card filename error

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#181]
Correct card file names are not accepted. Basically any name that starts with '.' is not getting accepted, when according to the specifications, it is valid.
![image](https://github.com/user-attachments/assets/cf0b47a6-c160-42b6-8d2e-0616bb196690)

This also hampers the account name usage, upon entering an account name that starts with '.' and giving no card filename, it doesn't create a default card file but generates the invalid card filename error.

For reference,
![image](https://github.com/user-attachments/assets/63f662c4-67e4-4e18-9512-346ff36a6b50)

**Comment by ushasree-3** [comment]
PR: #192 #193
