### ISSUE TITLE
Functionality bug(Group-9): Multiple accounts with same account name but different card

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#182]
Allows for the creation of accounts with same names but with different card filenames.
![image](https://github.com/user-attachments/assets/df269ea9-f8f1-4203-b187-25e3369a2f0b)

Only unique account names should be allowed, should raise an username already exists error.

**Comment by ushasree-3** [comment]
PR : #192 #193
