### ISSUE TITLE
Functional Bug(Group-9): Inconsistency while handling accounts with same names but different card files

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#183]
With the two account names as 'shubham' it doesn't let me interact with the second account card file, raising an invalid pin error, because these were initialized with different pins '1234' and '2345'
![image](https://github.com/user-attachments/assets/704c0a62-ee2e-4e4e-ad81-29470624f3c9)

But the accounts with name 'shubham2' it allows me to interact with both card files, because they were initialized with same pins '1234'.
![image](https://github.com/user-attachments/assets/14f1509a-985a-439e-b262-40f3f9bbc877)

This is an inconsistency functional issue.

**Comment by ushasree-3** [comment]
PR : #192 #193
