### ISSUE TITLE
Functional/Security Bug(Group-9)

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#184]
When two accounts are created with same name, but with different card file names, and initialized with same pin, it effectively treats them as one account instead of two separate accounts. 
So, if two people were to create an account with same name and accidentally same pins (with different card files obviously), then the system will treat them as one individual account. 
Either it should raise an error while account creation or treat them as two separate accounts

Below is an illustration where i create two accounts with name 'agrawal' and cardfiles as '1' and '2' and use same pin '1234' for both. Any transaction in one account is reflected in the other.
![image](https://github.com/user-attachments/assets/5f3bf9fb-01b9-44ba-a15f-277e98f881e5)

@bichhawat Sir, i don't know whether this is a security bug or a functional bug

**Comment by bichhawat** [comment]
Can you check what happens with different PINs for both the accounts created?

P.S. You have exhausted the limit for bug reporting for this group, so your count will be capped at 3 for this group.

**Comment by shubham-agrawal04** [comment]
With different pins, it creates the new card file, but always shows invalid pin while trying to access the account with the new cardfile.

**Comment by ushasree-3** [comment]
PR no. #192 #193
