### ISSUE TITLE
Functional Bug ( Group 10) Inconsistency

### ISSUE THREAD

**Issue by Vraj2811** [IITGN-CS431/project-cns#185]
The code runs even when the input is given in wrong order.

Even if I consider that it is ok, it creates wrong log file

![image](https://github.com/user-attachments/assets/a3c1eb49-b949-4e80-b9cc-1f0d7b5247a1)

So, the inputs given by me were "secret" -> "Alice" -> "log"
It should have created a log file named "log" with employee = "Alice"
But in the first case where it should have given an error, it created a log file named "Alice" with employee = "log"

**Comment by bichhawat** [comment]
But isn't that okay? The argument following -E is log in the first case so the system thinks that log is the employee and it is not expecting any argument after -A, which indicates arrival and hence uses Alice as the log name.

**Comment by Vraj2811** [comment]
Ok, I had misunderstood the way it was working.
But there is error some error in the way they are taking input between -A and and -E
For eg ->
![image](https://github.com/user-attachments/assets/7bbc88fe-4ca5-49e5-b188-2a2d6b694714)
It did not give any error when more arguments were passed

**Comment by aditya-me13** [comment]
@Vraj2811 this bug is already reported in #149

**Comment by Vraj2811** [comment]
My bug was that the code should take the input in order i.e. 1st should be integer for T, then string for Key , then string for Employee/Guest and finally string for the log file name
But it was giving wrong output, so I added some extra inputs to show the problem
It is different bug from yours @aditya-me13 
I had given more inputs to show that it is not following the order

This is the expected behavior ->
![image](https://github.com/user-attachments/assets/dd4abdf9-8446-4e08-ac57-d8052bc26423)

Bug ->
![image](https://github.com/user-attachments/assets/75bcbdd8-15f5-4e0d-83b8-ea9a7b0ca1ba)
I think that the inputs should be taken in order
@bichhawat, in this case according to what you had said, the argument following -E is log so the system thinks that log is the employee and it is not expecting any argument after -A,  and hence should use Alice as the log name but does not and gives error

**Comment by rovin99** [comment]
I don't think there is any new issue here. user is suppose to follow the order logappend -T <timestamp> -K <token> (-E <employee-name> | -G <guest-name>) (-A | -L) [-R <room-id>] <log>  if they don't the system is giving invalid error. 

> Ok, I had misunderstood the way it was working. But there is error some error in the way they are taking input between -A and and -E For eg -> ![image](https://private-user-images.githubusercontent.com/121240839/381100985-7bbc88fe-4ca5-49e5-b188-2a2d6b694714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODQzMDEsIm5iZiI6MTczMDQ4NDAwMSwicGF0aCI6Ii8xMjEyNDA4MzkvMzgxMTAwOTg1LTdiYmM4OGZlLTRjYTUtNDllNS1iMTg4LTJhMmQ2YjY5NDcxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxODAwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODgwMjI3YTdmMjYwZGUwNzAyYzVmYjc1N2I1ZDg3ZmEyMWQxYjQ4NGY1MjMxMzQzNWQ0MTQ3MzgwMTBjMjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h4rnK9BiK0eA2avQbYLLldPSvR8bZAbuE34VsBSqppc) It did not give any error when more arguments were passed

Regarding this case here the system was taking the last value, in this case log2 which has been fixed in issue #149 . Let me know if I am missing something @bichhawat sir.

**Comment by Vraj2811** [comment]
Basically, what I meant was:
1)  User is suppose to follow the order logappend -T 'time' -K 'key' (-A | -L)  (-E | -G) 'name' [-R] 'room' 'log'.
If it doesn't follow. It should give an error. But it does not give any error as shown below 
![image](https://github.com/user-attachments/assets/273b50eb-63b6-4035-9fee-1ad3d2b79e0d)

2) Now, if I assume that the above thing will not give any error as @bichhawat sir said "The argument following -E is log in the first case so the system thinks that log is the employee and it is not expecting any argument after -A, which indicates arrival and hence uses Alice as the log name."
Then when the same thing is used with -R , it should not give any error but it gives error. 
 
![image](https://github.com/user-attachments/assets/d2e3b2e5-c03a-4ae6-a9cd-4a8110aedee7)

So, there is a bug as one of the functionality is incorrect

**Comment by bichhawat** [comment]
I agree that either the order should not matter or if it matters, it should be the same in all cases. I am not sure what the reason is for the last logappend to fail but it needs to be explored as the arguments may not all be in order (which is perfectly alright) but should be parsed correctly

**Comment by rovin99** [comment]
Fixed order between A and E Flags with #255 
<img width="514" alt="Screenshot 2024-11-07 at 11 11 26 AM" src="https://github.com/user-attachments/assets/0bfe3c79-fadc-43a8-a52a-2f49c1796de7">
<img width="565" alt="Screenshot 2024-11-07 at 11 11 44 AM" src="https://github.com/user-attachments/assets/cb0dcf9d-e7b3-4656-a00c-ace1aa0b2715">
