### ISSUE TITLE
Functional Bug(Group-7):Invalid transaction amount being accepted

### ISSUE THREAD

**Issue by Pratham-Sharda** [IITGN-CS431/project-cns#187]
When i am adding a zero before the transaction it is not giving me error and is accepted which should not be the case according to the Spec

![image](https://github.com/user-attachments/assets/90876e16-3f80-4922-819a-41355834f541)
![image](https://github.com/user-attachments/assets/11b2f6ae-d408-4d9c-a077-0870c25eead3)

**Comment by RuchitJagodara** [comment]
please refer to the issue #168. It is identical to this issue.
