### ISSUE TITLE
Functional Bug (Group-7): Valid file name not being accepted

### ISSUE THREAD

**Issue by Pratham-Sharda** [IITGN-CS431/project-cns#188]
When i am giving a file name that is card file that is being created of 124 characters it is showing invalid which should not be the case as according to spec it should allow files up to length 127 length

![image](https://github.com/user-attachments/assets/ea1a3093-85ae-447f-897e-585bd07d6957)

**Comment by RuchitJagodara** [comment]
The .card extension is included in the file name count, resulting in a total filename length of 128 characters, which is not permitted.

**Comment by RuchitJagodara** [comment]
@bichhawat Should we modify this so that the additional 5 characters from ".card" in the filename are not counted? Our current code checks for a maximum filename length of 127 characters. If you believe this is not a bug, then we can proceed as is.

**Comment by bichhawat** [comment]
This should be okay. Please mention this in your README
