### ISSUE TITLE
Functional Bug(Group -7):Auth file is being created without following the restrictions on file names

### ISSUE THREAD

**Issue by Pratham-Sharda** [IITGN-CS431/project-cns#190]
File name is being created with characters like comma and lash which should not occur.

![image](https://github.com/user-attachments/assets/7ffa67e8-71c6-41ce-b5e8-66b584d03978)
![image](https://github.com/user-attachments/assets/3bb3a1de-8cad-4ac5-85c6-48d9bac21a15)

Also "." and ".." are being accepted as correct auth file names .

![image](https://github.com/user-attachments/assets/32ca1482-10eb-49d0-8f29-5ae3a4e0ad57)

**Comment by bichhawat** [comment]
Is it because it is ignoring any arguments passed to the bank program?

**Comment by RuchitJagodara** [comment]
I have added a pr for fixing this bug.

**Comment by RuchitJagodara** [comment]
> Is it because it is ignoring any arguments passed to the bank program?

Yes, it was the main issue.

**Comment by RuchitJagodara** [comment]
> Also "." and ".." are being accepted as correct auth file names .

I think this should not be an issue because we can actually create a text file with these names.

**Comment by Pratham-Sharda** [comment]
![image](https://github.com/user-attachments/assets/ee6ca74d-f490-4349-83b9-deb2c128bfce)
File names should not be made with these names 

> > Also "." and ".." are being accepted as correct auth file names .
> 
> I think this should not be an issue because we can actually create a text file with these names.

**Comment by RuchitJagodara** [comment]
Done !
