### ISSUE TITLE
Functional Bug(Group-7): By default card name functionality not implemented

### ISSUE THREAD

**Issue by Pratham-Sharda** [IITGN-CS431/project-cns#194]
![image](https://github.com/user-attachments/assets/de0b7651-6114-4ab6-b43d-c420c3c9001d)
![image](https://github.com/user-attachments/assets/0dc2508b-7bb4-4d39-8c54-869dea406b43)

So here when i am making a new account without specifying the card file name it should create a account with default card file name which is not happening in this case

**Comment by Pratham-Sharda** [comment]
Similarly the default functionality of bank.auth file has not been implemented
![image](https://github.com/user-attachments/assets/5e15e66b-81b9-477b-b249-1bf9f2d921d9)

![image](https://github.com/user-attachments/assets/09adfb90-9635-4a48-8762-0d5f80a94bbc)

**Comment by RuchitJagodara** [comment]
> Similarly the default functionality of bank.auth file has not been implemented ![image](https://private-user-images.githubusercontent.com/144925900/381079205-5e15e66b-81b9-477b-b249-1bf9f2d921d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjYxNTYsIm5iZiI6MTczMDM2NTg1NiwicGF0aCI6Ii8xNDQ5MjU5MDAvMzgxMDc5MjA1LTVlMTVlNjZiLTgxYjktNDc3Yi1iMjQ5LTFiZjlmMmQ5MjFkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwOTEwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjcxZDgzOGNiNzBlOGVkZjlhOTc0OTgwMTAwOTZiZWE5YTc2ZTAyMzZhYzBjZDFjNTVlMmRjZWM2NzM0ZGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GjXdkfp3gZ7sA_EQ8Tgi4ItRI07nzrlnnjynHfYVaus)
> 
> ![image](https://private-user-images.githubusercontent.com/144925900/381079268-09adfb90-9635-4a48-8762-0d5f80a94bbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjYxNTYsIm5iZiI6MTczMDM2NTg1NiwicGF0aCI6Ii8xNDQ5MjU5MDAvMzgxMDc5MjY4LTA5YWRmYjkwLTk2MzUtNGE0OC04NzYyLTBkNWY4MGE5NGJiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwOTEwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWM5NmNhYWEwYWMzNWQ4ZGRlOGZkMDczYWIzYjcwNjdkYjFjMjE5N2RkNGU3NGZkMGYzMDdiMjE0ZGMzMThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H1nsyJLngpvb9EL_Dor6naJwlrGs5rxsRMF2X2pLpfU)

I think you are running the atm here, instead of bank, because in my machine default file name functionality is working fine for bank although I agree with you regarding the atm bug.

**Comment by Pratham-Sharda** [comment]
![image](https://github.com/user-attachments/assets/8804cede-c6b8-4c5e-a4f8-f61144acd2ae)
But in the spec it is mentioned that if -s tag is not specified in the atm then by default it should take bank.auth as auth file name

**Comment by RuchitJagodara** [comment]
> ![image](https://private-user-images.githubusercontent.com/144925900/381907541-8804cede-c6b8-4c5e-a4f8-f61144acd2ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjkzODksIm5iZiI6MTczMDM2OTA4OSwicGF0aCI6Ii8xNDQ5MjU5MDAvMzgxOTA3NTQxLTg4MDRjZWRlLWM2YjgtNGM1ZS1hNGY4LWY2MTE0NGFjZDJhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxMDA0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjI2MmVmNDExMmEzYjE2MmQ4YzhiYzY0MmY4Nzg2MzdlM2Y2YmE0ZmI1YjFjNjcyMGVhYWZiZmE3M2E4MWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1MAyvFrA-J24eH_pHJFjhL3NTNok-Lajv9aGwgA0pMI) But in the spec it is mentioned that if -s tag is not specified in the atm then by default it should take bank.auth as auth file name

It is taking the bank.auth as default file path but in the [comment](https://github.com/IITGN-CS431/project-cns/issues/194#issuecomment-2443796676) you are running atm instead of bank as you mentioned you were checking this process for bank there.

**Comment by RuchitJagodara** [comment]
> ![image](https://private-user-images.githubusercontent.com/144925900/381077703-de0b7651-6114-4ab6-b43d-c420c3c9001d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzE3OTksIm5iZiI6MTczMDM3MTQ5OSwicGF0aCI6Ii8xNDQ5MjU5MDAvMzgxMDc3NzAzLWRlMGI3NjUxLTYxMTQtNGFiNi1iNDNkLWM0MjBjM2M5MDAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxMDQ0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjMzMjY0ZjhhZTM5MTQ2MDcyNTY5ODI0NmUyZGIwY2FkZGFkMDA2MDlhZmViNTM4NWJiZjM2MzFmYjljMTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-VqSV43sV0lwdZLlApM2rKo68X2c8Lb68LXnvI6wBH4) ![image](https://private-user-images.githubusercontent.com/144925900/381078014-0dc2508b-7bb4-4d39-8c54-869dea406b43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzE3OTksIm5iZiI6MTczMDM3MTQ5OSwicGF0aCI6Ii8xNDQ5MjU5MDAvMzgxMDc4MDE0LTBkYzI1MDhiLTdiYjQtNGQzOS04YzU0LTg2OWRlYTQwNmI0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxMDQ0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDc3MDE3ZjA2YmYwY2I3ZmVlNjM0ZmNhZDVjMDE2MGY5OGQ0MjVhMjg2M2Q0NmJmZTI0ODUxZmU1MjJkMGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VdjR-Cz66rQ0drqB49gQWG81KIP4Eo5w_obYKz55iFw)
> 
> So here when i am making a new account without specifying the card file name it should create a account with default card file name which is not happening in this case

I have fixed this bug.
