### ISSUE TITLE
Functional Bug(Group -7): Names with spaces are accepted in an absurd way without throwing any error 

### ISSUE THREAD

**Issue by Pratham-Sharda** [IITGN-CS431/project-cns#195]
![image](https://github.com/user-attachments/assets/0e72199e-62bb-42fc-a60e-34c433b47169)
Here when i give my name with space so instead of giving error it just accepts the first word as the username which should not be the case as it ignores the next part of the name with space ,instead it should throw error that this name is not valid.

**Comment by Pratham-Sharda** [comment]
![image](https://github.com/user-attachments/assets/31c929de-8e5d-4081-8d26-bcb166cd4e9a)
just another example with more than 2 words

**Comment by RuchitJagodara** [comment]
> ![image](https://private-user-images.githubusercontent.com/144925900/381084541-0e72199e-62bb-42fc-a60e-34c433b47169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjM4MzIsIm5iZiI6MTczMDM2MzUzMiwicGF0aCI6Ii8xNDQ5MjU5MDAvMzgxMDg0NTQxLTBlNzIxOTllLTYyYmItNDJmYy1hNjBlLTM0YzQzM2I0NzE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwODMyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjA0YTMyNWIzYzhjMGU0ZTVhNWNjODVkYjgxNDhkYWE5NzNkMGZhMGUzOGI1MTY4M2EyMGZkMDg2OTA2Njg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kEB-dJz913BmZWjN5ZIW8IXODVn40QD3stiR-_TIacI) Here when i give my name with space so instead of giving error it just accepts the first word as the username which should not be the case as it ignores the next part of the name with space ,instead it should throw error that this name is not valid.

Here, this is not a bug but instead it is a command line input problem, in general whenever we write any commands it splits commands with respect to spaces given in the command and here as you can notice it is ignoring the second word because it has been split and is not counted towards the input file name so after all it is some kind of trash word, so it is not giving any error and working fine.

**Comment by Pratham-Sharda** [comment]
Exactly my point it should not ignore the second word as giving spaces must give an error and other groups have ensured to give an error when spaces are given in the command line

**Comment by RuchitJagodara** [comment]
I believe we should consult the documentation instead of comparing our work with other groups. Please show me the relevant documentation that specifies this.

**Comment by RuchitJagodara** [comment]
> and as per the documentation is concerned I don't think spaces have been allowed and thus giving a name with space should throw out error.

However, a name with a space is not a single word. In commands, spaces are used to separate different words, making it a different input. Therefore, for the argument -a, it is being treated as part of the input, which is the usual behavior.

@bichhawat , can you please clarify what we should do in this case?

**Comment by bichhawat** [comment]
The file names accept `abc\ def` and `"abc def"` but I am not sure if `abc def` is an acceptable string. If the other two are accepted, I think it should be fine. If not, please clarify in the README
