### ISSUE TITLE
GROUP 3 - ATM Account Creation and Card File Conflict

### ISSUE THREAD

**Issue by heerkubadia** [IITGN-CS431/project-cns#199]
When I run the command to create an account , it successfully creates an account. 

```
heerkubadia@Heers-MacBook-Air-986 group-3 % ./atm -a hello -c hello.card -n 10.00   
Please enter your PIN: 
Account created successfully
{'account': 'hello', 'initial-balance': '10.00'}
```
Now when I try to make a new account with the same name, it throws an error which is expected.

```

heerkubadia@Heers-MacBook-Air-986 group-3 % ./atm -a hello -c hello1.card -n 10.00   
Please enter your PIN: 
Account with this name or card number already exists
```

According to the above error the account isn't created and so is the card file (card file with the same name was not created before). Still when I run the same command as above again ,it shows that card file already exists despite the first attempt at account creation failed. Thus even if the account isn't created , the card file gets created.

```
heerkubadia@Heers-MacBook-Air-986 group-3 % ./atm -a hello -c hello1.card -n 10.00   
Please enter your PIN: 
Error: hello1.card card file already exists, try something else
```

**Comment by Quantizate** [comment]
Thanks for pointing this out. Actually, we failed to mention it in our readme, could you please try it once without the `.card` part in option `-c`. 
![Screenshot 2024-10-30 at 10 07 18 AM](https://github.com/user-attachments/assets/19d09a18-79ce-4d35-9113-9a1488c2e5fb)

Although there won't be any hinderance in any of the operations, but we do need to take care of the extra card file creation. In our testing, we did ignore this as there was no hinderance in the working, we will take a look at it again. 

PS: CC'ing @YYashraj in the thread.
