### ISSUE TITLE
Security Bug  (Group-10) : Authentication Issue

### ISSUE THREAD

**Issue by Pranjal4697** [IITGN-CS431/project-cns#2]
# Security Bug - Any token can be used to append to the logfile (No Authentication Check)

## Description
We can create a log file using a particular token but next time while writing to the logfile  there is no authentication check , any token can be used to write to the logfile and during logread only the last token used can give us the entries (but only the entries appended by that token!). Therefore the original creator of the logfile cannot access the logfile and also the integrity of the logfile is compromised.

## Input Provided and Output Obtained
![image](https://github.com/user-attachments/assets/f7605747-3901-4afa-b028-7bf4fa2088be)
As we can see above, for same logfile (log1 in this case) and with different tokens (_secret_ in first case  and _password_ in second) we can append log entries (there is no authentication check) to the logfile which is a clear violation of token based authentication .

![image](https://github.com/user-attachments/assets/088b4cd1-8b8d-4bf0-8b65-8c8f7039ccfc)
Also as depicted in the above image, the user with original token is not able to use logread functionality and only the last token can be used for logread functionality (which only consider the entries appended by that token ) . So eventually the access of the original user is lost and integrity of the logfile is compromised due to authentication bypass.

## Expected Output
For any token other than the correct original token (which is used while creating the logfile) must result in an authentication check failed error and without knowing the token , no one should be able to write to the logfile. Also, both logread and logappend functionality should be accessible if someone uses the correct original token.

## Functionality Targeted as part of the test-case.
 Authentication and Logfile Integrity

_Bug Type: Security Bug
Concerned Group : Group-10
Reported by : Pranjal (21110160)_

**Comment by rovin99** [comment]
Bug Fixed.Now there is a auth check for different keys for same log.
<img width="555" alt="Screenshot 2024-10-24 at 10 52 51 PM" src="https://github.com/user-attachments/assets/7cc80aba-ec8d-4444-b9b8-d4027f9ef7fa">
