### ISSUE TITLE
Compilation Error [Group 11] 

### ISSUE THREAD

**Issue by AshStorm17** [IITGN-CS431/project-cns#20]
![{62695B99-F96B-490B-9234-BF3BA4D97A4B}](https://github.com/user-attachments/assets/de98bb17-2660-466a-8ddd-6da519ae2ca7)

The compilation returned with errors from the Server file.

**Comment by arpan004** [comment]
Fixed Compilation Error and generated the PR

**Comment by pratyush3757** [comment]
Whenever you refer something:
Please mention the PR number [#72] 
Similarly for the Error number (with the \# prefix) in the PR title.

**Comment by arpan004** [comment]
Ok sir next time we will take care

**Comment by pratyush3757** [comment]
Merged fix #72
