### ISSUE TITLE
Unnecessary card file creation - group 7

### ISSUE THREAD

**Issue by Jiya-desai** [IITGN-CS431/project-cns#205]
In the 2nd command that I ran, no card file should have created, because the account name had already been used. But a card file with the same name still got created, and hence I was not able to create a new account with that name again:

![image](https://github.com/user-attachments/assets/1b3c1b48-9ce8-4f5f-9015-0d11c2f59ee0)

**Comment by bichhawat** [comment]
I think this is okay. Creating additional card files should be fine, right? Please check if we can use this to perform unexpected activities or if there is anything against this in the spec. If so, reopen the issue.
