### ISSUE TITLE
GROUP 2 - Functionality issue - Valid log filename not getting accepted

### ISSUE THREAD

**Issue by lavanya2504** [IITGN-CS431/project-cns#206]
According to the spec, log's filename may be specified with a string of alphanumeric characters, including underscores and periods. But when I entered the log filename to be "..", it throws an error. 

```
lavanya04@DESKTOP-3IU7VB2:/mnt/c/Users/Lavanya/Downloads/project-cns-main/project-cns-main/project-submissions/group-2/build$ ./setup 234 ..
Invalid log file name: must be alphanumeric.
```

**Comment by naveeeeeeeeeen** [comment]
This is not a bug. I know periods and slashes are allowed in the log file name. But the file names such as dot dot dot (...)  or slash slash slash (///) without any other alphanumeric characters are not allowed. 
This was done **deliberately** to make sure the clients do not create hidden files. (dot slash) is used to reference files present in other directories which you can do. Also you can create files with names like log.123, log.pdf, log.png, log.log etc
![Screenshot from 2024-10-29 22-31-54](https://github.com/user-attachments/assets/3e6d001f-c183-4652-8f0d-74bd4f3f34f7)

**Comment by bichhawat** [comment]
@naveeeeeeeeeen Please mention this in your readme.

**Comment by naveeeeeeeeeen** [comment]
> @naveeeeeeeeeen Please mention this in your readme.

Done.
