### ISSUE TITLE
GROUP 2 - Absurd error occurs on a valid command line input

### ISSUE THREAD

**Issue by lavanya2504** [IITGN-CS431/project-cns#209]
When I try to arrive on campus using an employee name and a room number that has never been previously used in a new logfile, it throws an error saying "Invalid:  Are you on campus? You must leave the room first before entering another room."

```
lavanya04@DESKTOP-3IU7VB2:/mnt/c/Users/Lavanya/Downloads/project-cns-main/project-cns-main/project-submissions/group-2/build$ ./setup 234 LOG3
Using existing key from secret.key.
Setup Done. Remember Your Password.
lavanya04@DESKTOP-3IU7VB2:/mnt/c/Users/Lavanya/Downloads/project-cns-main/project-cns-main/project-submissions/group-2/build$ ./logappend -T 12 -K 234 -E LavanyaSharma -A -R 1011 LOG3
invalid: invalid: Are you on campus? You must leave the room first before entering another room.
```

**Comment by Chess-shrutiDubey** [comment]
We made the error comment like this only. **It's not an error** . Anyone before entering into the room ,must first enter into the campus that why the error is asking you are you in campus...?  
If someone enter into room directly, it should throw invalid error, and exactly that is what it is throwing.
