### ISSUE TITLE
Functionality Issue : Group 9

### ISSUE THREAD

**Issue by aayush8991** [IITGN-CS431/project-cns#21]
The Get_Balance function does not return any value, i.e., the field remains empty in spite of showing success message.
The balance should be 2000, however it does not return anything.
![image](https://github.com/user-attachments/assets/ba5ffb6d-a8f8-4c6e-af75-50f8960bd830)

**Comment by ushasree-3** [comment]
We have fixed this bug. If it is working now, kindly close the issue.

**Comment by bichhawat** [comment]
Please provide the PR number, too

**Comment by ushasree-3** [comment]
#45 <https://github.com/IITGN-CS431/project-cns/pull/45>
