### ISSUE TITLE
Security Bug (Group-6): Loss of Data on file tampering

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#216]
This system doesn't support server-client connection and hence all the interactions happens at one machine only.
I can easily tamper with the log files that are created(as I have access as a client), though they contain the information in encrypted manner, it allows me to write some gibberish text into the log files. 

When those files are tampered with, the system generates a 'integrity violation' error, and doesn't allow to either logread or logappend with that particular logfile. This, according to me, is a loss of data as there's no way of reading or extracting the logfile contents, and is security breach. 
![image](https://github.com/user-attachments/assets/b0020b60-b383-42e0-8fc4-cd22b4755181)

This is security bug because of the loss of data and no backup. For example, if 100 of guests enter the institute, their log data is lost (and all other employee log data is lost too, obviously) which could result into unaccountability of guests residing and their actions.  

I feel this can be prevented by using a server-client mechanism or some other method, which allows data to be restored in some way

**Comment by bichhawat** [comment]
This is okay as long as you cannot read the data. There was no client-server requirement here so I believe this should be fine

**Comment by shubham-agrawal04** [comment]
@bichhawat Sir, but if any user is able to freely tamper the files and that leads  to complete loss of data for the entire system of that particular log file, then it should be an issue. 
This may seem a small issue but suppose this happens to a banking system and they lose all their clients' data, then that would be a major concern. 
I am not saying that they need to use server-client model, but they should ensure security from loss of data
