### ISSUE TITLE
Security Bug : Group-6

### ISSUE THREAD

**Issue by shubham-agrawal04** [IITGN-CS431/project-cns#217]
This system doesn't support server-client connection and hence all the interactions happens at one machine only.
As a result, if I remove any logfile explicitly, what happens? Because I can do so, since I have access as a client/user.

Upon removal of the logfile, the system stills allows me to freely interact with that particular logfile using logappend, without raising any error, it works smoothly. But when I try to run the logread command with that particular logfile, it says 'Unable to open log file'. 

It should ideally check if files exists or not, and then only proceed. My best guess is that this system only checks whether or not the logfile in question appears in the 'logfile_metadata.json' or not, and then take action accordingly, because this json stills contain the same data before and after. Only after I remove the logfile data from json file, then it creates a new file with that name, and continues working correctly.
![image](https://github.com/user-attachments/assets/08524907-efe9-49be-b733-fc17e0c596c2)

**Comment by bichhawat** [comment]
I am not sure I understood the last few commands. Please elaborate a little

**Comment by shubham-agrawal04** [comment]
After a file is removed, the code doesn't check if the file actually exists in the system or not, it only checks whether its data is present in the .json file or not.
So when i remove a file, it still allows me to interact freely with logappend without raising any error, while trying to logread it raising the error of 'Unable to open the file'.
In the last few commands, I went and edited the .json file to remove the information about the logfile named 'log1' to show that only after doing that it works correctly by creating a new file. If that is not done, then the code assumes that file exists, without checking if it actually exists or not.

**Comment by Pranjal4697** [comment]
I don't think it is a bug as such. When a file is deleted , everytime the logappend is used for that file, it exit with an error to indicate the user that something is wrong with the file and  logread is not able to read because the file does not exists.
![image](https://github.com/user-attachments/assets/6ea91cbb-104a-4817-ab02-2905962c88e4)

We can also add print statement "File no longer exist" along with exiting the logappend program for more clarity (if you suggest so). 

What you did by deleting the json entry provides a way for the user to again create a logfile with same filename (knowing that the previous file is deleted).

**Comment by shubham-agrawal04** [comment]
I mean you should definitely show some error message, because how else will the user know if the command they are running is working or not? 

You don't return any success message if it works and you don't print any error message if it doesn't work, how am i supposed to know what's working and what's not? If someone logappends all day long, they will just assume that it is working correctly, because of no error response, but when they check at last at the end of day by logreading, they find that file is not found. That's a major security flaw.

My point is, logappend should check if the file really exists or not, and if not it should raise an error.

**Comment by shubham-agrawal04** [comment]
In normal cmd terminal, there is no way of knowing if the command was working or not(see my screenshot in the first message), unlike in terminal of VS Code as you showed.

**Comment by Pranjal4697** [comment]
We have fixed this issue. Now after deleting a log file , when we use logappend or logread for that file , it will show up the error message as shown below.

![image](https://github.com/user-attachments/assets/f9c3c18d-a656-481a-9802-2c191b193685)
