### ISSUE TITLE
Functionality Bug ( Group 2 )  Accepting invalid key names

### ISSUE THREAD

**Issue by Vraj2811** [IITGN-CS431/project-cns#219]
![image](https://github.com/user-attachments/assets/5155882c-dd82-49d4-8e91-3bbc6a2c0b81)

It is accepting non alphanumeric char in the secret key. It is even accepting spaces as secret key. They have only checked for hyphens and not any other non-alphanumeric char 
![image](https://github.com/user-attachments/assets/83a098b0-2e0b-4f18-83f9-8778a0fa25cf)

**Comment by naveeeeeeeeeen** [comment]
RESOLVED 
PR Number : #228  #227 

![Screenshot from 2024-10-30 17-41-10](https://github.com/user-attachments/assets/5d37c293-b49d-4017-bccf-3f7ee9f622c6)
