### ISSUE TITLE
Functionality issue: Accepting more than 2 decimal places in number input (Group 5)

### ISSUE THREAD

**Issue by Quantizate** [IITGN-CS431/project-cns#22]

**Comment by Quantizate** [comment]
![Screenshot 2024-10-24 at 5 01 07 AM](https://github.com/user-attachments/assets/202191c9-e29a-4e0b-8407-138a11c10a84)

**Comment by bichhawat** [comment]
Please provide a proper description of the bug along with the expected output.

**Comment by Quantizate** [comment]
Will this be treated as an issue as the documents mentioned that the more than 2 decimal places aren't allowed. [valid inputs](https://github.com/IITGN-CS431/project-cns/blob/main/atm/index.md#valid-inputs)

**Comment by Quantizate** [comment]
Awaiting your reply for the same @bichhawat sir
