### ISSUE TITLE
Security Bug ( Group 10 ) 

### ISSUE THREAD

**Issue by Vraj2811** [IITGN-CS431/project-cns#221]
While using the logappend function on an imp file, it should generate an error if the file already exists. However, instead of raising an error, it currently writes to the file. The function should first check for the existence of the file and ensure it does not already exist before proceeding.

![image](https://github.com/user-attachments/assets/dabc01f6-2447-4c26-b970-efd5d6745460)

**Comment by bichhawat** [comment]
The bug would be if you are able to open and read from the file without using logread. Otherwise, this should be okay, right?

**Comment by bichhawat** [comment]
Modifying an existing file should be okay, as far as it does not allow the other person to read it without logread. We are currently not concerned with the other files on the system.

**Comment by Vraj2811** [comment]
Consider an example where there is a program designed to print the current date and time to a file named now.txt within a folder. If the logappend command is run with now.txt specified as the log file, whether by accident or intentionally, it will function correctly during the initial run.

However, issues arise when the date-printing program writes to now.txt again. This action modifies the file, rendering it unusable for both logappend and logread commands. This creates a significant problem: files in the folder that are not intended as log files can be modified at any time, leading to potential data corruption or loss.

To address this, it is important to ensure that only designated log files are considered for logappend and logread operations. This prevents unintended modifications and maintains data integrity.

[Screencast From 2024-11-07 18-48-31.webm](https://github.com/user-attachments/assets/55e8c5bb-0213-41a5-b4ef-8b946a929581)

As seen in the video, the file now.txt was made first and was used by temp.py. But the logappend could also access it and modify it. And finally the file got corrupted and there is data loss

**Comment by Vraj2811** [comment]
@bichhawat please look into this

**Comment by bichhawat** [comment]
I understand the issue but I am not sure if this is a security bug as far as the designed application is concerned because the logging application need not know about what files are there in the folder. If existing log files are modified because of this, then it may be an issue, but if I understand correctly, this does not happen.

**Comment by rovin99** [comment]
Now Fixed with #284 
<img width="749" alt="Screenshot 2024-11-16 at 12 17 16 AM" src="https://github.com/user-attachments/assets/81f461f9-cfce-4302-b274-27cd9ad50248">
