### ISSUE TITLE
GROUP 3 - Incorrect Handling of Withdrawals with Amounts Truncated to Zero

### ISSUE THREAD

**Issue by heerkubadia** [IITGN-CS431/project-cns#223]
When I try to withdraw an amount with more than 2 decimal places, it truncates it and then processes the request as seen below 

```
heerkubadia@Heers-MacBook-Air-986 group-3 % ./atm -a test -c test -w 2.00011
Warning: Only 2 decimal places are supported. Truncating amount.
Withdrawal successful
{'account': 'test', 'withdraw': '2.00'}
heerkubadia@Heers-MacBook-Air-986 group-3 % ./atm -a test -c test -g        
Current Balance
{'account': 'test', 'balance': 9.0}
```

Since withdrawal of 0.00 isn't allowed it throws an error

```
heerkubadia@Heers-MacBook-Air-986 group-3 % ./atm -a test -c test -w 0.00   
Error: Invalid combination of operation modes
```

From the above two, if I try to withdraw 0.00011, expected behaviour is the amount should get truncated and become 0.00 and thus throw an error -` Error: Invalid combination of operation modes`. But instead the request gets processed and shows insufficient balance.

```
heerkubadia@Heers-MacBook-Air-986 group-3 % ./atm -a test -c test -w 0.00011 
Warning: Only 2 decimal places are supported. Truncating amount.
Insufficient balance
```

**Comment by YYashraj** [comment]
This transaction is not actually being processed on the database. The incorrect message has to do with a mistake on handling the status-code.
@heerkubadia Thanks for pointing this out!
