### ISSUE TITLE
Security Bug(Group-2) Denial of service

### ISSUE THREAD

**Issue by VenkatReddybathuni** [IITGN-CS431/project-cns#224]
Upon trying to establish connection between server and 2 different clients, only the first clients commands are getting executed while the second connections is not getting any response upon giving commands

**First Client**:

![image](https://github.com/user-attachments/assets/2142fb3a-eed9-4f7d-838f-e11cf5693d85)

**Second Client**:

![image](https://github.com/user-attachments/assets/d00f31f2-50c7-4605-9a93-4901309bf2c4)

**Sever**:

![image](https://github.com/user-attachments/assets/81376252-b335-4d91-ab0b-d47dac3948ff)

Here the server is responding and giving service to only one client(i.e the first connected one) and the second clients commands are not being executed.

Note that this is not the same as #220 because in #220 the server shuts down when the client closes his connection. Here multiple clients are not given access even when the server is on and working

**Comment by naveeeeeeeeeen** [comment]
**BUG RESOLVED**
![Screenshot from 2024-11-01 20-59-44](https://github.com/user-attachments/assets/1c36da1a-e62d-44b0-9a6b-04bcbecc44ea)
