### ISSUE TITLE
Leading zeros are considered as valid input - Group 3

### ISSUE THREAD

**Issue by carbonvibes** [IITGN-CS431/project-cns#229]
According to the design specifications, leading zeros are permitted only in the fractional part of the amount and should be considered valid input exclusively in that context. However, currently, leading zeros are also accepted in the whole number part of the amount as well as in the PIN number, which does not align with these specifications.

<img width="976" alt="Screenshot 2024-10-30 at 7 24 03 PM" src="https://github.com/user-attachments/assets/ab26e554-2514-4df8-b4e7-70fb7d6ef5f5">

ATM SIDE:
<img width="731" alt="Screenshot 2024-10-30 at 7 33 16 PM" src="https://github.com/user-attachments/assets/0461f64d-0e2f-4b34-b3fb-66c5e7da2fe4">

Also, this applies to the PIN as well. (0000) is considered as a valid PIN.

**Comment by bichhawat** [comment]
Kindly clarify in the README or update the code accordingly.

**Comment by Quantizate** [comment]
@carbonvibes we have just taken an assumption wherein we are removing the leading zeros, I don't think the octal or hexadecimal can be used there, its just that we are making some good considerations from the input and accepting that. 
As for the pin, I don't think leading zeros is actually a problem, we could have a pin 0000 its just something that we have introduced where the only constraint is numbers within the length 4-6.

**Comment by carbonvibes** [comment]
I believe we are all expected to strictly follow the design specifications, which clearly state that leading zeros are only permitted in the fractional part of the amount field and not elsewhere. This applies to the whole number part of the amount. For instance, one might argue that allowing amounts with more than two decimal places is an “additional feature.” However, this would still be considered a deviation from the design specs, which clearly define valid inputs. In the same way, accepting leading zeros where they are not specified as valid input goes against the design and should be treated as a problem I believe.

**Comment by pratyush3757** [comment]
I can't say about PINs as they aren't in the spec. Rules for that are for the implementers to decide.

But leading zeros in the amount and other places are being considered as decimal numbers instead of octal.
So, octal "042" is being considered as decimal "42". Are hex inputs being converted to decimal or are being rejected?

Either way, @Quantizate please update the README with the relevant behaviour. Or maybe just reject the input with leading zeros.

**Comment by Quantizate** [comment]
Thanks for the insights, we will add it to the readme. All the leading zero inputs are converted to decimal instead of being rejected.
