### ISSUE TITLE
Functionality Issue: Card File creation error (Group 5)

### ISSUE THREAD

**Issue by Quantizate** [IITGN-CS431/project-cns#23]
![Screenshot 2024-10-24 at 6 58 15 PM](https://github.com/user-attachments/assets/b3e87d0a-3544-4423-a1ca-4e107db4b2a6)
![Screenshot 2024-10-24 at 6 58 26 PM](https://github.com/user-attachments/assets/83c6722f-fb8a-445f-ba03-36a77beb3127)

**Comment by AshStorm17** [comment]
There might been a communication error in between the communication process due to various reasons. In such a case the transaction would have been rolled back. Kindly, check if there was an inconsistency in the transaction.

Also the given details are insufficient to conclude that a bug exists in the code. Request you to provide more details on the issue.

**Comment by Quantizate** [comment]
The communication is happening and we also see a successful account creation message, owing to that if a file isn't created then i believe a bug persists. PFA attached the docker file so you can test it yourself too. 

```
# Use an official Ubuntu as a parent image
FROM ubuntu:20.04

# Set environment variables to avoid user interaction during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install dependencies
RUN apt-get update && \
    apt-get install -y \
    g++ \
    libssl-dev \
    libmysqlcppconn-dev \
    libcurl4-openssl-dev \
    libpthread-stubs0-dev \
    cmake \
    make \
    wget \
    mysql-server \
    libjsoncpp-dev \
    && apt-get clean

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Copy the init_db.sh script into the container
COPY init_db.sh /app/init_db.sh

# Make the init_db.sh script executable
RUN chmod +x /app/init_db.sh

# Build the application
RUN make

# Expose the MySQL port
EXPOSE 3306

# Expose the application port (if applicable)
EXPOSE 3000

# Start MySQL and the application
CMD /app/init_db.sh && ./bank
```
the init_sql file for the same

```
#!/bin/bash

# Start MySQL server
service mysql start

# Wait for MySQL to be ready
until mysqladmin ping -u root --password='my-secret-pw' &>/dev/null; do
  echo -n "."; sleep 1
done

# Ensure the root user has the necessary privileges and correct authentication method
mysql -u root --password='pass' -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'pass';"
mysql -u root --password='pass' -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;"
mysql -u root --password='pass' -e "FLUSH PRIVILEGES;"

# Create the database if it doesn't exist
mysql -u root --password='pass' -e "CREATE DATABASE IF NOT EXISTS atm_bank_db;"

# Initialize the database
mysql -u root --password='pass' atm_bank_db < /app/init_db.sql
```

**Comment by Quantizate** [comment]
Plus with this being the code 

```
if (sendSSLRequest(ssl, requestStr, response, auth_key))
        {
            std::cout << response << std::endl;
        }

        std::istringstream responseStream(response);
        std::string firstWord;
        responseStream >> firstWord; // Read the first word

        // Create the card file with the a random PIN code
        std::ofstream newCardFile(cardFile);
        if (firstWord == "Error")
        {
            std::remove(cardFile.c_str());
        }
        else
        {
            if (newCardFile)
            {
                newCardFile << pin_code;
                newCardFile.close();
                std::cout << "Card file created with PIN: " << pin_code << std::endl;
            }
            else
            {
                std::cerr << "Error creating card file." << std::endl;
            }
        }
        ```
        we clearly see that we get a good response as account is created and then, we also see that according to the message construct from the backend, there is no "Error" as the first word and in the else case there is an issue with the new card construct.

**Comment by aayush8991** [comment]
In response to your first message, we tried implementing the same commands. The output we are getting is :
![WhatsApp Image 2024-10-24 at 9 15 29 PM](https://github.com/user-attachments/assets/979d4f6d-b754-4626-a5b0-a409cd758590)
Since you have not given the card file, it will take the default name a.card, and the default of the auth is a bank.auth.

**Comment by bichhawat** [comment]
I guess this is sorted out, @Quantizate please close if this is addressed.

**Comment by Quantizate** [comment]
Actually sir, this was an error. I had run several dos and different attacks and tried to run this code again which lead to mostly which i'm assuming to be system errors.

**Comment by Quantizate** [comment]
Based on my findings using a ssl testing tool, since no rate limiting is applied the code is vulnerable to Dos threats. Following which I ran load testing and dos attacks through apache benchmark and locust(python).

![Screenshot 2024-10-25 at 1 14 05 PM](https://github.com/user-attachments/assets/252bfe92-08d1-48ce-95d6-9a332cefe98e)

Here, I have printed both client and server side ouputs (the json data being sent and the final response data being sent during create have just been printed to verify) and post that we also get a message that the Account is being created successfully. 
![Screenshot 2024-10-25 at 1 15 38 PM](https://github.com/user-attachments/assets/c050b512-60bb-433b-b648-969fed742977)
Revisiting the code construct mentioned above we do see that if there were a communication error then we would have no response (in this case "Account Creation Successful" is the response) and post that we do see that if there were some communication error occurring based on the code we would have a remove card file construct. But, the code is going into the else case wherein here its the error from the new card file creation, which i presume could have occurred through the system overload. I use a MacOs system to make sure i used linux as recommended by the team and also remove the system invariance, I have used a docker container for the same and used some initialisation scripts for mysql settings. (Both the dockerfile and script is mentioned above). I wouldn't like to reveal more details of the attacks (the commands used etc, on the issue page). 

![Screenshot 2024-10-24 at 5 01 14 AM](https://github.com/user-attachments/assets/958dcd22-654d-46ec-9b5f-a092384329fb)

**Comment by Quantizate** [comment]
@bichhawat sir, please check the above message. Waiting for your response for the same.

**Comment by bichhawat** [comment]
If I understand correctly, the second part is a separate issue and not related to the first part. If so, please open a new issue with the appropriate details. If not, please provide a minimum working example, which can help reproduce the issue.

**Comment by Quantizate** [comment]
But, sir the code just doesn't run on the docker even on a fresh try. I've been facing issues with that. Also, given the restriction that I can only open 3 bugs for a group can I still add the Dos threat as a new bug?

**Comment by bichhawat** [comment]
The threat is not a bug; you will need to provide concrete evidence that the code is vulnerable to make it a bug. If you find one, please open a new issue and close this one if you want to. 

For the docker issue, please discuss with the group once. I am not sure what the issue is but their code has been running on other systems.
