### ISSUE TITLE
Functionality error: Account name validity error (Group 5) 

### ISSUE THREAD

**Issue by Quantizate** [IITGN-CS431/project-cns#24]
Both "." and ".." are valid account names. 

![Screenshot 2024-10-24 at 7 07 05 PM](https://github.com/user-attachments/assets/543142d7-fee5-4091-8ec4-d88802e6a750)

**Comment by bichhawat** [comment]
Please elaborate what is supposed to be the expected output. If . and .. are not accepted (and may be some other special folder names), then it should be okay. But if it is creating an account name "." and not accepting this, it would be an issue.

**Comment by AshStorm17** [comment]
This issue was fixed with PR #29. Kindly close the issue.

**Comment by Quantizate** [comment]
Based on the valid inputs, "." and ".." are valid account names but not valid file names.
