### ISSUE TITLE
Functionality Bug( Group 9):  Unused specified card file 

### ISSUE THREAD

**Issue by PrateekG93** [IITGN-CS431/project-cns#244]
There is a critical flaw in the account handling and card file verification system. When creating an account, a corresponding card file (e.g., alice6.card for account alice6) is generated. However, it has been observed that actions intended for alice7 can be performed using the card file of alice6, which implies that the system does not correctly verify or restrict operations based on the card file associated with each account.

![PHOTO-2024-11-03-20-35-56](https://github.com/user-attachments/assets/952cbe8b-951a-4d74-8cc5-939a3839640c)

The system does not enforce the uniqueness of card files per account, allowing any card file to be used for any account, provided the card file exists. This means that an attacker with access to any single card file could potentially access and manipulate other accounts.

 Each account should be exclusively accessible with its corresponding card file. For example, only alice7.card should authorize access to alice7's account, and alice6.card should only authorize access to alice6's account.

**Comment by bichhawat** [comment]
The card file seems to be ignored as the manipulation happens on the correct account as seen in the output. This is not a security bug but could be a functionality bug.
