### ISSUE TITLE
Issue (Group 12): Makefile Formatting Error

### ISSUE THREAD

**Issue by PrateekG93** [IITGN-CS431/project-cns#245]
I followed the instructions provided in the README file to set up the build environment. However, when I attempt to run make, I encounter an error: Makefile:17: missing separator. Stop. This error typically indicates a formatting issue in the Makefile, often caused by spaces being used instead of tabs to indent command lines. Despite adhering to the README's instructions, this error persists, suggesting there may be an inconsistency in the Makefile's formatting.

<img width="1428" alt="Screenshot 2024-11-04 at 12 09 45 AM" src="https://github.com/user-attachments/assets/4f3f3067-facc-4590-a5b9-acfc0370dd94">

**Comment by chakrie1489** [comment]
![image](https://github.com/user-attachments/assets/cac9ab6e-76ba-4116-abf8-2edcfa539f64)

Fixed.
