### ISSUE TITLE
Functionality Bug (Group 7): Allows Invalid Transaction Amounts of 0.00 for Deposits and Withdrawals

### ISSUE THREAD

**Issue by PrateekG93** [IITGN-CS431/project-cns#246]
The ATM client currently permits deposits and withdrawals of 0.00, which contradicts the specified requirement that deposit and withdraw amounts must be greater than 0.00.

![image](https://github.com/user-attachments/assets/b8f4f474-7258-42bf-8ad7-3b8b7bcca5df)

The system should reject any deposit or withdrawal requests of 0.00 and display an error message indicating that the amount must exceed 0.00.

**Comment by PrateekG93** [comment]
Sir, I have a doubt regarding the status of a bug I reported. Group 7 initially acknowledged the issue and marked it as resolved (issue no.  #134). However, after rechecking their code, I found that the bug still exists.

When I raised the issue again, it was marked as a duplicate, but there are no currently open issues addressing this. Could you please clarify that shouldn't this still be considered a bug since Group 7 already reported it as fixed, and there is no current open issue addressing it?

**Comment by bichhawat** [comment]
@RuchitJagodara @Hit2737 please check and let me know if these issues exist in your current code

**Comment by RuchitJagodara** [comment]
> @RuchitJagodara @Hit2737 please check and let me know if these issues exist in your current code

Yes, we fixed this earlier, but just I saw that the commit which we pushed didn't include the updated code for deposit and withdraw, so the code was there in my local machine but was not updated on the upstream branch. I sincerely apologise for the mistake.

**Comment by RuchitJagodara** [comment]
I have added and pushed that commit now.

**Comment by bichhawat** [comment]
@RuchitJagodara Please update the PR number here

**Comment by RuchitJagodara** [comment]
@bichhawat I changed the code and directly pushed my changes. I didn't make any PR.
