### ISSUE TITLE
Functionality Bug (Group 7): Program Hangs Indefinitely Due to Lack of Timeout or Error Handling in Network Connection

### ISSUE THREAD

**Issue by PrateekG93** [IITGN-CS431/project-cns#247]
When running the program with network parameters, it attempts to connect to the specified IP address without a timeout or appropriate error handling mechanism. If the target IP address (e.g., 192.0.2.1) is unreachable or invalid, the program does not return an error message or exit gracefully. Instead, it enters an indefinite waiting state, requiring the user to forcibly terminate the program (using Ctrl+C).

![image](https://github.com/user-attachments/assets/0bd1ca03-b523-4b87-b34e-5a8d1cdda68e)

Expected Behavior: The program should detect connection failures within a defined timeout period and provide an informative error message.

**Comment by bichhawat** [comment]
Not sure if this is a bug as the timeout may depend on how the TCP connections are setup. If the IP address is valid, it will try multiple times.

**Comment by PrateekG93** [comment]
I understand that TCP connections generally attempt multiple retries before timing out, depending on network configuration. However, the specification explicitly states that the ATM client should observe a 10-second timeout if there’s no response, and it should exit with return code 63. This behavior is expected regardless of the underlying TCP retries.

<img width="962" alt="Screenshot 2024-11-04 at 11 48 09 AM" src="https://github.com/user-attachments/assets/3620b2cd-e663-44da-b15f-e6f7b03a3468">

Currently, the program does not meet this requirement, as it hangs indefinitely without timing out or exiting as specified. This discrepancy between the actual behavior and the specified requirement led me to categorize it as a bug.

Please let me know if I’ve misunderstood any aspect of the specification.

**Comment by RuchitJagodara** [comment]
Fixed !

**Comment by bichhawat** [comment]
@RuchitJagodara the commit shows that no file has changed. Kindly verify and let me know what the status is

**Comment by RuchitJagodara** [comment]
Here, is actual commit, here it is showing the final commit but when you click the commit then you can see the parent commit also, so in below commit I changed my code for this.

021777b41fbf7ca5aa46f060c0a35db947e56e33
