### ISSUE TITLE
Security Bug(Group -12): No authentication while log modification and log reading

### ISSUE THREAD

**Issue by PrateekG93** [IITGN-CS431/project-cns#249]
The code of group - 12 allows unauthorised users to modify and read log files without proper authentication. The issue arises due to the lack of authentication checks when using the logappend and logread commands. As shown in the provided screenshots, an attacker can append data to the logs and later read the logs without requiring valid credentials.

<img width="1124" alt="Screenshot 2024-11-04 at 3 54 53 PM" src="https://github.com/user-attachments/assets/5de28613-19ee-4bee-af66-d63ce78e67d1">
<img width="944" alt="Screenshot 2024-11-04 at 3 59 39 PM" src="https://github.com/user-attachments/assets/448847ea-58b4-4112-9cf1-a56aa7ec866d">

This vulnerability could allow an attacker to tamper with log data, potentially modifying critical logs or gaining access to sensitive information. Such actions can compromise the integrity and confidentiality of log files, impacting overall system security and auditability.

**Comment by aditya-me13** [comment]
Although it is not concerned with my group, I do not understand what exactly is the bug here. With the right ```secret``` corresponding to the ```log8```, the user can modify and read logs. Anyone with the right ```secret``` to the log-file can modify and read logs.

The screenshots provided do not explain the bug to me. Please let me know what am I missing.

**Comment by bichhawat** [comment]
Agree with Aditya that the issue is not clear here. What does missing valid credentials mean here?

**Comment by aditya-me13** [comment]
I don't think that was asked to be implemented. It's like using your google account without two-step verification. Anyone with the right password can login and make the required changes. It is assumed that the key is the only way of authorization as well as authentication in case of Security Guard Project. Key leakage cannot be considered as a bug from application side, rather a mistake from client side.

@bichhawat sir please correct me if I am wrong.

**Comment by bichhawat** [comment]
Yes, I am not sure how can you verify who they are. It does require the valid secret to be provided before allowing the write. If you can write without the secret, that is the missing credential, if I understand correctly.
