### ISSUE TITLE
Security Issue (Group 2): Possible Eavesdropping and Credential or Secret Exposure.

### ISSUE THREAD

**Issue by cpatel321** [IITGN-CS431/project-cns#256]
The security guard application has a secret which is necessary for reading and writing the logs. The adversary can easily find out secrets by sniffing the transmitted packets as there is no encryption over SSL. Also, the client application is a very simple one and can be substituted by this very simple command.
```
nc <server-ip> <port>
```
Adversaries can easily append to logs and read them. 

The following is the screenshot from Wireshark application, showing the exposure of the secret. 
![{6CE3A152-399C-4461-8A39-10B16CD361A8}](https://github.com/user-attachments/assets/dc75cd42-ac9c-447a-910e-2d7152e274e5)

If you wish you can access the TCP dump [file](https://drive.google.com/file/d/17B1q8AP0Rl-2_-dW9Ie4-57zSDDJEAB9/view?usp=sharing).

**Comment by naveeeeeeeeeen** [comment]
**RESOLVED**
PR Number: #259  #260  #261 


![Screenshot 2024-11-13 220607](https://github.com/user-attachments/assets/f2c6e64f-6fb0-419f-a893-20e974b40c59)
