### ISSUE TITLE
Functionality bug: Invalid port number accepted (Group 9)

### ISSUE THREAD

**Issue by Quantizate** [IITGN-CS431/project-cns#26]
![Screenshot 2024-10-24 at 7 32 28 PM](https://github.com/user-attachments/assets/14c94a66-5d37-48d2-a785-ee1efebb82e5)

**Comment by bichhawat** [comment]
What is the issue here and the expected output?

**Comment by Quantizate** [comment]
The valid ports are specified as number from 1024 and 65535 inclusively. [link](https://github.com/IITGN-CS431/project-cns/blob/main/atm/index.md#valid-inputs)

**Comment by ushasree-3** [comment]
PR no.s : #105 #103
