### ISSUE TITLE
Security Bug (Group 2)

### ISSUE THREAD

**Issue by Vraj2811** [IITGN-CS431/project-cns#266]
The server-client interface functions as a remote desktop, enabling me to execute commands on the server remotely from the client side.

![image](https://github.com/user-attachments/assets/c067fd17-e65a-494c-a82f-df6cbae1f637)

As shown in the image above, I have full access to the server's files and the ability to delete any files on the server.

**Comment by bichhawat** [comment]
Not sure I understood the problem. Please elaborate

**Comment by Vraj2811** [comment]
[Screencast From 2024-11-14 14-39-32.webm](https://github.com/user-attachments/assets/0bafd2ea-ebb3-482f-887b-866e67c719b5)

As demonstrated in the video, I have full access to the server through the client. I was able to delete all files in the directory using client.py. This presents a significant security vulnerability, as it allows me to delete not only log files but also main applications like logappend and logread.

**Comment by Chess-shrutiDubey** [comment]
**Solved the issue.**

![WhatsApp Image 2024-11-14 at 3 32 13 PM](https://github.com/user-attachments/assets/d5aeac68-005a-4090-a598-6709d30c0a6a)
