### ISSUE TITLE
[Functionality Bug] Group-8 : Server is not accepting valid commands.

### ISSUE THREAD

**Issue by naveeeeeeeeeen** [IITGN-CS431/project-cns#269]
**Client side:**

Client1:
![group8](https://github.com/user-attachments/assets/3299ac9d-c98c-4f6b-87cc-1041b7959f56)

Client2:
![Screenshot from 2024-11-14 18-11-07](https://github.com/user-attachments/assets/3d2cb71b-a64b-4565-862b-a6d8965869e4)

**Server side:**
![Screenshot from 2024-11-14 17-59-20](https://github.com/user-attachments/assets/eb714610-4948-4a0a-b050-7cb1c671634d)

**The code is not working as expected.
I tried with different clients but even with valid commands, Sever keeps stopping and keeps giving "SSL read error".**

**Comment by Kishan-Ved** [comment]
I am not able to reproduce this error, everything works fine on my laptop.
![image](https://github.com/user-attachments/assets/3241609f-67d9-4c1e-a5f4-4f8fa87f894c)

**Comment by Kishan-Ved** [comment]
I also tried to reproduce this by running the client and server on different laptops. Everything seems to work fine.

![image](https://github.com/user-attachments/assets/20ab4f47-1f0f-44bd-8796-05abc799162f)

**Comment by Kishan-Ved** [comment]
Please ensure that you are running the latest code (if not, please pull the latest code and try again). This is because you are receiving `invalid command or not implemented`, but that functionality is added.  Also, please ensure that you are on a stable network and there are no huge timeouts.

If this still persists, please send a video recording so we can reproduce this error. Additionally, please send a text file with your commands (as you might be including some weird whitespaces)

**Comment by naveeeeeeeeeen** [comment]
Here is the screen recording: https://drive.google.com/file/d/1gjKj1a-Rgzu_sPm2geizCdOLkyRADLeR/view?usp=sharing

**Comment by cpatel321** [comment]
Dear [naveeeeeeeeeen](https://github.com/naveeeeeeeeeen), 
We are still not able to reproduce this bug. Please let us know if you find any significant step in our process, as soon as possible. 

[Video link](c:\users\chand\We are still not able to reproduce the bug.mp4)

**Comment by naveeeeeeeeeen** [comment]
> Dear [naveeeeeeeeeen](https://github.com/naveeeeeeeeeen), We are still not able to reproduce this bug. Please let us know if you find any significantly different steps in our process, as soon as possible.
> 
> [Video link](https://drive.google.com/file/d/1_wdgaU-5RsmaPl_QvHJvV08cm2VWdvBm/view?usp=sharing)

The steps in the video are completely wrong. 😂
Please provide a different link.
This is not the video you wanted to share I reckon.

**Comment by cpatel321** [comment]
> > Dear [naveeeeeeeeeen](https://github.com/naveeeeeeeeeen), We are still not able to reproduce this bug. Please let us know if you find any significantly different steps in our process, as soon as possible.
> > [Video link](https://drive.google.com/file/d/1_wdgaU-5RsmaPl_QvHJvV08cm2VWdvBm/view?usp=sharing)
> 
> The steps in the video are completely wrong. 😂 Please provide a different link. This is not the video you wanted to share I reckon.
link is updated

**Comment by naveeeeeeeeeen** [comment]
I tried running your project in some other system and it's working fine. 
The 'ssl read error' pops up only when I try to run it in my system.
I am closing this issue.
Thankyou!
