### ISSUE TITLE
Functionality bug: Invalid card file created (Group 9)

### ISSUE THREAD

**Issue by Quantizate** [IITGN-CS431/project-cns#27]
![Screenshot 2024-10-24 at 7 41 43 PM](https://github.com/user-attachments/assets/3d1dd475-938f-40e5-9f04-d3499d9223b9)

**Comment by bichhawat** [comment]
Please provide the expected output, too, and some more description. The bug may not always be clear based on the output screenshots

**Comment by Quantizate** [comment]
"." and ".." are valid account names but not valid file names. [link](https://github.com/IITGN-CS431/project-cns/blob/main/atm/index.md#valid-inputs)
