### ISSUE TITLE
[Functionality BUG] Wrong IP address is HARD CODED - Group 2

### ISSUE THREAD

**Issue by RuchitJagodara** [IITGN-CS431/project-cns#271]
Here, in server.py file and client.py file which are main executable files the group has hard coded a random IP address `10.7.23.164` and Port `12345`.  And as we are not allowed to temper with the code, I can't change the IP and Port here, as it is not allowed so basically if I run the file as it is it is giving me error, which should not happen by default because I am not missing anything here so it should work but it is giving error because of the same reason !

![Screenshot from 2024-11-15 00-50-43](https://github.com/user-attachments/assets/5b82391e-7e10-424c-9249-6d98155944f2)
![Screenshot from 2024-11-15 00-50-53](https://github.com/user-attachments/assets/612a2880-a1ed-4fc1-8b44-3d87cfb6315e)

Here, is the ss of error message.

![Screenshot from 2024-11-15 00-53-55](https://github.com/user-attachments/assets/cbd57ec8-112d-4826-a810-94d984e88991)

Although I agree that they have mentioned that we should use our own IP but still this should be considered as a bug because I can't change the code as it is tempering with the code ! 

![Screenshot from 2024-11-15 00-46-05](https://github.com/user-attachments/assets/37a83e0e-2ae1-4906-8daa-a468abe8ded2)

And here instead of mentioning it, I think it is better to change the code to handle the default IP and Port according to values it can actually take without any errors like taking IP as 127.0.0.1 and port as any random value which is available !

**Comment by naveeeeeeeeeen** [comment]
**Issue resolved, Now you can provide ip and port number directly.**

![Screenshot from 2024-11-15 15-18-03](https://github.com/user-attachments/assets/957b19fd-3b5b-42de-8a44-ac9418763072)
![Screenshot from 2024-11-15 15-18-27](https://github.com/user-attachments/assets/b8bb0dba-2a36-4a52-8a21-ff1bd1cd0af5)

**Comment by RuchitJagodara** [comment]
Thank you for the update ! @bichhawat can you please mark this as a bug ?
