### ISSUE TITLE
Security Bug ( Group 2 )

### ISSUE THREAD

**Issue by Vraj2811** [IITGN-CS431/project-cns#273]
[Screencast From 2024-11-15 10-42-52.webm](https://github.com/user-attachments/assets/2412928d-3354-439a-877b-bfda79a49930)

In the video, commands like ./logread are encrypted using RSA, requiring decryption with the private key before execution. However, the output from these commands is displayed in plain text, without encryption.

**Comment by naveeeeeeeeeen** [comment]
**This is not a bug per se. Clients do not have access to private key.
And you are just using the private key to decrypt it.**

P.S. The commands received will not be shown in the latest code.

**Comment by Vraj2811** [comment]
Yeah, I used the private key to decrypt it, but that's not what I'm pointing out. If you check, the output from logread isn't encrypted and shows up in plain text.

**Comment by naveeeeeeeeeen** [comment]
Yes, That was done deliberately. Output doesn't need encryption.
It is to be shown in plain text.

**Comment by Vraj2811** [comment]
If this was done on purpose, it’s a big problem because securing command outputs is super important. Even if it wasn’t intentional, it still makes the system vulnerable to eavesdropping.

**Comment by bichhawat** [comment]
So is the claim here that the responses from the server to the client are unencrypted?

**Comment by Vraj2811** [comment]
Yes

**Comment by bichhawat** [comment]
If the data is sent unencrypted over the network, it is a bug that needs to be resolved because anyone can now read the data violating the confidentiality requirements.
