### ISSUE TITLE
Group 7 : Allowing Deposit of Amount 0.00

### ISSUE THREAD

**Issue by arpan004** [IITGN-CS431/project-cns#289]
The application permits the deposit of an amount equal to 0.00, even though the specification [**(Reference)**](https://github.com/IITGN-CS431/project-cns/blob/main/atm/atm.md) states that the deposit amount must be greater than 0.00

![image](https://github.com/user-attachments/assets/55cea413-3f75-49a1-8bd0-f287db098cf2)

**Expected Behavior:**
The system should reject the transaction and display an error message stating that the deposit amount must be greater than 0.00.

**Comment by RuchitJagodara** [comment]
@arpan004 what is atm1 here? Because we have not provided any file with that name.

**Comment by arpan004** [comment]
Actually, there seems to be a version issue when running the ATM file directly, so I need to recompile the code using the file name "atm1".

**Comment by RuchitJagodara** [comment]
I have fixed the issue, you can check it now, thank you for reporting the BUG !
