### ISSUE TITLE
Functionality Bug (Group 9): Card File Name Validation Issue

### ISSUE THREAD

**Issue by PrateekG93** [IITGN-CS431/project-cns#290]
The system incorrectly allows creating a card file named ".", violating the project specifications. 

<img width="1012" alt="Screenshot 2024-11-17 at 6 42 38 AM" src="https://github.com/user-attachments/assets/adfdf797-9262-48e4-af21-ae92dad17f1c">

This bug allows the invalid name ".", as shown in the screenshot

![image](https://github.com/user-attachments/assets/ce818029-2fb0-4db1-8092-cf246b039546)

**Comment by bichhawat** [comment]
The file name here is not "." but "..txt", which is valid
