### ISSUE TITLE
Group 7: Application Hangs When Card File Name Exceeds Certain Length

### ISSUE THREAD

**Issue by arpan004** [IITGN-CS431/project-cns#291]
The application hangs indefinitely when the card file name provided in the command exceeds a certain length. This behavior prevents the system from proceeding further, leaving the user with no feedback or error messages. Despite waiting for 20 seconds or more, the application does not produce any output, does not disconnect, and remains unresponsive.

![image](https://github.com/user-attachments/assets/a50db609-c320-488e-9629-81e47554076d)

**Comment by arpan004** [comment]
I can't get any response, even after waiting for a long time; it just keeps showing "Connecting with the Bank Server..."

**Comment by arpan004** [comment]
I pulled the branch yesterday, so my local copy is up to date as of then.

**Comment by RuchitJagodara** [comment]
But as you can see I tried the same input but it is working fine for me. Can you show me how you were running the bank?
