### ISSUE TITLE
Group 1: Account Creation Fails with "Invalid Amount" Error Despite Valid Input

### ISSUE THREAD

**Issue by arpan004** [IITGN-CS431/project-cns#293]
When attempting to create an account, the system consistently returns an "Invalid Amount" error, even when a valid initial deposit amount is provided. This occurs even if the amount matches the example format provided in the prompt (e.g. 123.45).

![image](https://github.com/user-attachments/assets/25617ccf-ab34-4d91-a739-8abea09fad27)

**Comment by Jiya-desai** [comment]
This was due to the upload of an older version of our code in the last commit, thanks for pointing it out. We have uploaded the latest versions which are (hopefully :p) working fine.
