### ISSUE TITLE
Bug[group-9] : Authentication System Permits Use of Mismatched Auth Files

### ISSUE THREAD

**Issue by ishikajain212** [IITGN-CS431/project-cns#295]
This issue is similar to the bug reported in #287. When the bank server is run with bank1.auth and the ATM client with bank.auth, the connection is still successfully established. However, it should not be accepted, as the authentication files do not match. This indicates that the ATM client is not being properly authenticated by the bank server, leading to a serious security vulnerability.

![image](https://github.com/user-attachments/assets/45c51fd4-1a3a-42ee-8729-a78e03761c60)

![image](https://github.com/user-attachments/assets/43cb4ed5-26fa-4c2d-a384-db4b5e3347a2)

**Comment by Saloni576** [comment]
I think you were running the server with bank.auth initially and then you are running the server on bank1.auth otherwise this issue won't come. If you are doing that then please follow the instructions on README of our project. If you are still getting the same issue then please let me know.

**Comment by ishikajain212** [comment]
The sequence of authentication files does not appear to matter in this case. Since I stopped the bank using `bank.auth` and then initialized it with `bank1.auth`,then why this would not be considered an issue?

**Comment by Saloni576** [comment]
Our ATM code checks for existence of auth file. If its not there then it raises an issue. It's how we have designed it and to run a new server without any errors or misfunction please refer to README.

**Comment by Saloni576** [comment]
If the issue is resolved after reviewing the README, kindly close the issue.

**Comment by ishikajain212** [comment]
According to me, the auth file is used to verify the legitimacy of both the bank and the ATM. If the bank and ATM are using different authentication files, it should result in an error, as they need to share the same file to ensure proper authentication and secure communication.
If the ATM only verifies the existence of the auth file, how does the system ensure the legitimacy of the ATM?

**Comment by Saloni576** [comment]
Legitimacy of ATM is checked during HMAC Authentication which requires secret key not bank.auth.
