### ISSUE TITLE
Functionality Bug[Group-1]: Hardcoded Port Number

### ISSUE THREAD

**Issue by Chhavigoyal02** [IITGN-CS431/project-cns#297]
The code has the port 8080 hardcoded for the bank server. This creates a problem when port 8080 is already in use (e.g., by a temporary server, as shown in the attached screenshot). Since the port is fixed, the bank application cannot run unless the source code is manually modified to change the port.

![image](https://github.com/user-attachments/assets/f804c07d-2844-4379-bee2-c3691187eef5)

![image](https://github.com/user-attachments/assets/ffa8057a-35c8-4990-89bf-14d8a96518ca)

**Comment by heerkubadia** [comment]
please refer to issue #18

**Comment by Chhavigoyal02** [comment]
@bichhawat sir but if we see issue #90 it is marked as a bug.

**Comment by heerkubadia** [comment]
Well we do have the option of taking server ip address as input from the user
