### ISSUE TITLE
Functionality Bug (Group-2): Invalid Room ID Accepted (logappend)

### ISSUE THREAD

**Issue by dkshjn** [IITGN-CS431/project-cns#3]
# Functionality Bug (Group-2): Invalid Room ID Accepted (logappend)
## Description
The system allows appending an entry with an ```invalid room ID``` (-1), which violates the specification that room IDs should be non-negative integers. Even though the room ID is invalid, the entry is still added to the log and later shown by logread. There is no validation in place to check the correctness of the room ID, leading to incorrect entries in the log.

## Demonstration
As shown in the attached image, the system accepts a log entry with an invalid room ID ```-1```. The logappend command processes the entry without checking the validity of the room ID, and the logread command displays the invalid room ID in the output.

<img width="709" alt="Screenshot 2024-10-23 at 11 00 34 PM" src="https://github.com/user-attachments/assets/d2e5f1b7-7c5a-4ac4-9495-8a287b666e6b">

Reported by: Daksh Jain(22110066)

**Comment by naveeeeeeeeeen** [comment]
I have Fixed this bug and Created a pull request.
Sample Output:-
![Screenshot from 2024-10-24 11-48-17](https://github.com/user-attachments/assets/833814f5-f869-4ed6-a784-ad145c5814a2)

**Comment by bichhawat** [comment]
Resolved
