### ISSUE TITLE
Functionality Bug (Group-7): Invalid amount being deposited

### ISSUE THREAD

**Issue by nishishah05** [IITGN-CS431/project-cns#302]
The specifications say: "Numeric inputs are positive and provided in decimal without any leading 0's (should match /(0|[1-9][0-9]*)/). Thus "42" is a valid input number but the octal "052" or hexadecimal "0x2a" are not. Any reference to "number" below refers to this input specification."
The code is allowing $01.00 to be deposited while it should throw an error.
![image](https://github.com/user-attachments/assets/eb175bac-0630-4bdc-905e-4242e2e82da3)

**Comment by nishishah05** [comment]
![image](https://github.com/user-attachments/assets/c9c074ea-a5b7-4a46-9e28-149775f4b9f7)
(from index.md)

It is stated that any deviation from these specifications (in this case, the 'number' specs, refer to point 2 and 3) should result in a 255 error.

**Comment by RuchitJagodara** [comment]
Fixed !
