### ISSUE TITLE
Bug[Group-2]: Room Revisit Not Logged Correctly

### ISSUE THREAD

**Issue by ishikajain212** [IITGN-CS431/project-cns#306]
When revisiting a room after leaving, the log only records the room visit once, regardless of how many times the room is re-entered. This behaviour suggests the system is not maintaining an accurate record of multiple visits to the same room.

Ideally, the behaviour should align with the example provided in the `Examples.md` file shared by the Sir.

![image](https://github.com/user-attachments/assets/c2d5cd08-f25e-4290-a19e-2c4431b47d92)

This is how the code is working.

I have used the same commands provided by the sir, but the output differs.
![image](https://github.com/user-attachments/assets/8dff95ab-ace1-469c-9fdc-76a505e2d900)

![image](https://github.com/user-attachments/assets/c27dc3f0-8a4c-45e8-89b4-e1cda1a7352b)

**Comment by naveeeeeeeeeen** [comment]
**Bug Resolved**

![Screenshot from 2024-11-20 14-27-46](https://github.com/user-attachments/assets/12c8583a-1f6b-43d4-846a-22fff59fefe1)
