### ISSUE TITLE
Functionality Bug - Group 12

### ISSUE THREAD

**Issue by Demolus13** [IITGN-CS431/project-cns#307]
![group-12-bug-3](https://github.com/user-attachments/assets/9fa60e74-b8f8-451b-8a23-20c1baac8676)

I am able to logappend into logappend without any invalid response
and when I read logappend I cannot get my desired output either

I feel it is important to maintain the logs seperate from actual working code

**Comment by bichhawat** [comment]
Please provide a little more description on what the expected output is

**Comment by Demolus13** [comment]
I am able to logappend into a log named "logappend" that too with same timestamp and no invalid response 

And when I try to read using logread
As I have tried to enter alice in the campus 2 times
I should see the below when I use logread 
alice

But either it didn't get appended means my log file wasn't created and no invalid response 
Or it got appended but isn't able to read it as it doesn't even try to show integrity issues

**Comment by chakrie1489** [comment]
This appears to be the same issue as #303 . Additionally, it seems you are running an outdated version of our code, which is likely causing the difference in outputs for the same input. Please update your local repository to the latest version.

**Comment by chakrie1489** [comment]
Fixed
