### ISSUE TITLE
Functional Bug - Group - 12

### ISSUE THREAD

**Issue by Demolus13** [IITGN-CS431/project-cns#309]
![group-12-bug-4](https://github.com/user-attachments/assets/34a8648a-9481-4ff6-80ff-5214d5c15522)

When I try to pass an Invalid token it does show Invalid but the log file gets created and I am able to read with a different key as well

**Comment by bichhawat** [comment]
You already have 3 reported bugs against this group; hence, this and any other bug from group 12's code would not count. Sorry about that
