### ISSUE TITLE
Functionality issue: Accepting more than 2 decimal places in amount (Group 9)

### ISSUE THREAD

**Issue by YYashraj** [IITGN-CS431/project-cns#31]
![image](https://github.com/user-attachments/assets/e7aafc55-01d1-4d96-b0a3-39c020a7c58a)
![image](https://github.com/user-attachments/assets/f6a2caf9-4ea4-4226-9500-a23978d4fa57)

**Comment by bichhawat** [comment]
This may be okay as long as it is not creating issues.

**Comment by YYashraj** [comment]
It won't cause a problem but it violates the third point mentioned in the system [requirements](https://github.com/IITGN-CS431/project-cns/blob/main/atm/index.md#valid-inputs). So wouldn't this be an issue?

**Comment by bichhawat** [comment]
yes, sorry about that.

**Comment by bichhawat** [comment]
Please provide the PR number, if fixed

**Comment by ushasree-3** [comment]
#103 #104 #105
