### ISSUE TITLE
Security Bug (group-7): Application vulnerable to replay attacks as no nonce or timestamps are used while authentication.

### ISSUE THREAD

**Issue by cpatel321** [IITGN-CS431/project-cns#311]
The user can increase it's account money by intercepting packets sent by atm to the bank and replay them without depositing anyting. 

Please find the attached [video](https://drive.google.com/file/d/12LksC0Xk7PFRAP8GGfz1DqyvafvPPeD6/view?usp=sharing). 

Also, you may look at the [python script](https://drive.google.com/file/d/1pHNHt7e-aqd1NkKLaNtxRX4ROSorHYjt/view?usp=sharing) used to replay packets. 

Also the attack screenshot clearly shows that the only atm thread I have open is not used, some malicious script is performing the replay attack.
![replay](https://github.com/user-attachments/assets/b7645346-196c-4e89-9ac3-dad257d1dc1e)

**Comment by RuchitJagodara** [comment]
Fixed !
