### ISSUE TITLE
Functionality Bug (Group 10): Persons state inconsistency

### ISSUE THREAD

**Issue by VenkatReddybathuni** [IITGN-CS431/project-cns#320]
John was entered into a room as an Employee but when I try to use a command which uses John as Guest it is not showing any invalid or error message meaning the guest John left the room without being on campus

![image](https://github.com/user-attachments/assets/536ddfb8-23f5-4818-a007-37cf967a3db0)

Ideally for the command

```./logappend -K secret -T 5 -L -R 0 -G John log2```

There should have been a error saying the person is not on campus

**Comment by rovin99** [comment]
Now fixed with #329 
<img width="454" alt="Screenshot 2024-11-21 at 9 15 36 AM" src="https://github.com/user-attachments/assets/3e3c6a19-4e79-4e92-91e5-bf88e58ffefa">
