### ISSUE TITLE
Functinality Bug or Security Bug - Group 2

### ISSUE THREAD

**Issue by Demolus13** [IITGN-CS431/project-cns#321]
![group-2-bug-2](https://github.com/user-attachments/assets/f82d3bbf-6a5f-42d5-b5ab-e2df9596820d)

I am able to setup the password of my log file with a not alphanumeric character
in this case my log2 has the password a\na

and then I am able to access the same file with another passord ana (which doesn't contain slash)
in this case I can make modification in log2 using the password ana but my set password was a\na

**Comment by naveeeeeeeeeen** [comment]
**Bug Resolved**

![Screenshot from 2024-11-20 14-29-49](https://github.com/user-attachments/assets/f22e505c-6919-43dc-abe3-936350988253)
