### ISSUE TITLE
Security Bug (Group-2): Client was able to send commands even after the server is shut down and has the power to shut the server down

### ISSUE THREAD

**Issue by VenkatReddybathuni** [IITGN-CS431/project-cns#322]
In the first part of the below attached image, the server was started and was shut down. Later I was able to send commands from the client and it was actually getting updated. U can see the commands I sent in client image and the recieved command message confirming the commands execution. 

![image](https://github.com/user-attachments/assets/67227a7a-9e49-415e-8223-d5966f9860d1)

![image](https://github.com/user-attachments/assets/d29bd8ec-2c5d-4c4e-b1fe-97c806e5f56b)

Later when I shut down the server, it still accepted commands like in the above explanation but wierdly the server was shutdown when I shutdown the client automatically.

![image](https://github.com/user-attachments/assets/682c150b-b465-4e85-8c71-280fd5ce858d)

![image](https://github.com/user-attachments/assets/c570ecf1-496e-4cc6-a41c-d47f1a066f8b)

Conclusion: When I try to shut down the server it wont shut down but when I shut down the client after I attempt to shut down the server, server shuts down leaving a serious security flaw in controlling the servers operation.

**Comment by naveeeeeeeeeen** [comment]
**Bug Resolved**

![Screenshot from 2024-11-20 14-31-22](https://github.com/user-attachments/assets/45c3d76d-0c75-4f5f-aa0b-b6438616d9ff)
