### ISSUE TITLE
Functionality issue: Card file with specified name is not created (Group 9)

### ISSUE THREAD

**Issue by YYashraj** [IITGN-CS431/project-cns#33]
![image](https://github.com/user-attachments/assets/00d57cbb-aa82-4a97-99a6-0c5a12f792e9)

**Comment by bichhawat** [comment]
Please provide the expected output and more description of the bug

**Comment by YYashraj** [comment]
When creating their account the users are given the option to specify the name for their card-files.
Here we can see that I have specified _bor.card_ to be the cardfile name for the account _meet_.
However, the system is creating a card with a different name. 
This hampers any further transaction the user (_meet_ here) would want to make.
