### ISSUE TITLE
Functionality Issue: Multiple transactions taken as valid input; Performing only one (Group-9)

### ISSUE THREAD

**Issue by YYashraj** [IITGN-CS431/project-cns#34]
![image](https://github.com/user-attachments/assets/f5ce0360-bae3-4e02-b0dd-a66f36e70eb6)

**Comment by bichhawat** [comment]
Please provide the expected output and more description of the bug

**Comment by YYashraj** [comment]
The program should either support only one transaction each command, or provide all required logs in order otherwise.

If first idea is implemented, then this command should not be executed on the server and throw and error.
Else for the second one, it should have shown logs for the execution status of both commands sequentially, i.e., 
{"account":"yash","withdraw":10.00}
{"account":"yash","deposit":3.00}

Running the command displayed above indicates that the ATM program accepts multiple transactions (namely withdrawal and deposit) but is only performing one of them.
