### ISSUE TITLE
Authentication Issue [Group 1] : Connection Hijacking Attack

### ISSUE THREAD

**Issue by AshStorm17** [IITGN-CS431/project-cns#35]
![{1A5D071B-31D9-4A9C-9138-A630FAF89CBD}](https://github.com/user-attachments/assets/e8cdd65b-1fa9-4917-8f49-828714c4ef78)

When a wrong key is sent in atm_auth_file the atm throws a error and exits, while the bank also throws an error.
In case I send an empty atm_auth_file the atm never returns, nor the bank throws an invalid connection error.
The code enters a somewhat infinite loop.

After its I ran another atm
![{F8E73CEA-6DAA-456D-9655-17B1798EB3FF}](https://github.com/user-attachments/assets/22077fd6-f43d-4d16-9268-60e73f4df097)
But since the previous atm and bank communication has not returned, the new connection is unable to be setup.
Hence the bank becomes unavailable for the time period until the first bank crashes or closes.

Thus the connection between the bank and the atm has been hijacked.

**Comment by AshStorm17** [comment]
After the PR #89 the issue still seems to persist. @Pratham-Sharda kindly see below.

![{62F1D644-8F55-4ADC-A8A7-F3DBB50ADFF3}](https://github.com/user-attachments/assets/d0a982aa-7eec-480d-8da0-4fdb36bda088)

There is a warning that the file is empty, but the atm is still running and thus another atm is not able to connect to the bank, until this atm has been killed.

![{3D403FAF-647C-4FE4-9C01-B6BC8532481F}](https://github.com/user-attachments/assets/4272b3d7-9304-425b-9222-39cd9238b9f3)

**Comment by bichhawat** [comment]
@AshStorm17 please check if the issue is resolved
