### ISSUE TITLE
Functionality Issue: Doesn't distinguish between Employee and Guest inside a Room (Group 10)

### ISSUE THREAD

**Issue by Demolus13** [IITGN-CS431/project-cns#36]
![group-10-bug-1](https://github.com/user-attachments/assets/47a194b3-6983-4e77-b943-a041eab8d981)

Here there are two "alice" an Employee and a Guest, but when printing the logs it shows only one slice inside the room

**Comment by saikarna913** [comment]
bug is fixed in pull request #59
