### ISSUE TITLE
Functionality Issue: Doesn't allow the entry of same name but of different category (-E or -G) (Group 12)

### ISSUE THREAD

**Issue by Demolus13** [IITGN-CS431/project-cns#37]
![group-12-bug-1](https://github.com/user-attachments/assets/082e7a8d-3f35-4d31-8f0c-0dfe2c0d1c8f)
Here alice entered as an employee but isn't able to enter as a guest and same for bob

**Comment by chakrie1489** [comment]
Fixed.
