### ISSUE TITLE
 Functionality Bug (Group-2): No Client-Server Communication, Logs Appended Locally

### ISSUE THREAD

**Issue by dkshjn** [IITGN-CS431/project-cns#4]
#  Functionality Bug (Group-2): No Client-Server Communication, Logs Appended Locally

## Description
The current implementation appends log entries directly to a local file without any form of **network communication** or client-server architecture. This means all log entries are **written to the local system** and not transmitted over a network, eliminating the possibility of **network attacks**. This also limits the ability for multiple clients or devices to append entries to a shared log file on a central server, as the log is written locally.

## Demonstration
In the first image, we can see the log file is opened directly, and the encrypted entry is written without any network communication.

<img width="752" alt="Screenshot 2024-10-23 at 11 05 41 PM" src="https://github.com/user-attachments/assets/4691cb8d-edd0-47a4-9030-1f1f0b5bc63f">

The second image shows the resulting log1 file with encrypted entries.
<img width="641" alt="Screenshot 2024-10-23 at 11 12 07 PM" src="https://github.com/user-attachments/assets/30163256-137b-4a59-9cae-438595032948">
Reported by: Daksh Jain(22110066)

**Comment by Chess-shrutiDubey** [comment]
The current design intentionally appends log entries directly to a local file without any form of network communication, as there were no specific requirements or guidelines in the project scope to implement a client-server architecture for log transmission. This local logging approach has the following benefits:

Security: Writing logs locally eliminates the risk of network-related vulnerabilities, such as man-in-the-middle attacks or data interception during transmission.
Simplicity: This design reduces complexity, especially in environments where only one client or device is responsible for logging, thereby ensuring quick access and minimal configuration.
However, if a client-server model is needed, we can extend the current implementation to support transmitting log entries to a central server, allowing multiple clients to append entries to a shared log.

**Comment by bichhawat** [comment]
Agreed. We are looking for bugs where any attempt to learn something about the log’s contents, or to change them, without the use of the logread and logappend and the proper token is allowed
