### ISSUE TITLE
bank.auth file not authenticated by the bank (Group - 7)

### ISSUE THREAD

**Issue by carbonvibes** [IITGN-CS431/project-cns#42]
Bank Side:
<img width="1127" alt="Screenshot 2024-10-24 at 10 24 32 PM" src="https://github.com/user-attachments/assets/2e82f6b8-f493-43c9-8ddd-83512ac3a0b8">

ATM Side: 
<img width="821" alt="Screenshot 2024-10-24 at 10 24 50 PM" src="https://github.com/user-attachments/assets/0f2e37a0-1d70-4d19-9d92-64a65b7d2849">

I created a file called dummy.auth with some random text and used it to authenticate with the ATM application. Surprisingly, the application accepted this file and allowed me to create a bank account and perform transactions without any issues. The problem is that the application doesn’t properly verify the .auth file. Any file, even with random content, is accepted as a valid authentication file. Ideally, only the official bank.auth file should be recognized and allowed by the bank for authentication. However, in the current setup, any file is treated as valid, which means the authentication process is not secure and can be easily bypassed.

**Comment by RuchitJagodara** [comment]
@bichhawat can You please mark this issue as duplicate because this is identical to the issue #11 which was fixed earlier.
