### ISSUE TITLE
Security Bug (Group 8) : All the log entries and passwords are present the build/logs folder as plaintext json data.

### ISSUE THREAD

**Issue by naveeeeeeeeeen** [IITGN-CS431/project-cns#47]
![Screenshot from 2024-10-25 00-54-22](https://github.com/user-attachments/assets/f1ce3db1-89d0-49d9-8198-b3b422fc8a19)
**Major security flaw as all the log entries and passwords/tokens are present in the build/logs folder as plaintext json data.
Anyone can read or alter the data.
No Encryption implemented.**

**Comment by cpatel321** [comment]
If you are able to access backend from the client side, then it's a problem. Backend access to the client is not expected.

**Comment by bichhawat** [comment]
The data should not be accessible unless logappend or logread is used to access it with the correct authentication file. Please fix this.

**Comment by bichhawat** [comment]
Is the log on the client side or server side? If it is server side, then it is okay.

**Comment by Kishan-Ved** [comment]
@bichhawat Sir and @naveeeeeeeeeen,
Our application is such that one laptop acts like the server, and another laptop (client) connects to it using the IP address. When a new client tries to connect for the first time, we ask the client to enter the server's IP address and a secure (encrypted) connection is made. 

All the log files are made and stored in the server's  laptop. The client can only access them via the `logread` command. There is no other way for the client to read/tamper those files.

**Comment by cpatel321** [comment]
@bichhawat I have also implemented the functionality to encrypt log files. Although all the logs were server side, there was no need to implement this. 
I have created a pull request with ID #119 . If you think this is a security bug and our group's points will be deducted, then only accept the PR, otherwise don't as the new changes may atttract new bugs.

**Comment by bichhawat** [comment]
I have merged the PR (it looked fine) although the earlier enforcement was okay.

**Comment by cpatel321** [comment]
@bichhawat I think this issue is resolved. Please mark it closed.
