### ISSUE TITLE
Functionality Issue(Group 8): Both -L and -A flags are allowed together and Both -E and -G are also allowed together

### ISSUE THREAD

**Issue by Chess-shrutiDubey** [IITGN-CS431/project-cns#48]
**Both -L and -A flags are allowed together** 
![WhatsApp Image 2024-10-24 at 11 59 31 PM](https://github.com/user-attachments/assets/075e2520-31e2-461c-9535-e0055ef3291c)
**Both -E and -G are also allowed together**
![WhatsApp Image 2024-10-25 at 12 14 09 AM](https://github.com/user-attachments/assets/6b9f97fe-f037-4f94-828a-bf6c30d70f5c)

**Comment by bichhawat** [comment]
Please provide more description to help the team fix this

**Comment by Kishan-Ved** [comment]
Fixed
