### ISSUE TITLE
Functionality Issue(Group-8) Leading Zeroes are not being dropped  

### ISSUE THREAD

**Issue by Chess-shrutiDubey** [IITGN-CS431/project-cns#49]
![WhatsApp Image 2024-10-25 at 12 14 09 AM (1)](https://github.com/user-attachments/assets/57897998-aa9a-4bba-ae2b-57baac2f1585)
**Entries are stored with leading zeroes and when we remove the person from the room we have to mention the leading zeroes's room number again.
As you can see in the attached image shown 000005 but when read shown 5 and when executed leave room command as 5, it give invalid room event.**

**Comment by Kishan-Ved** [comment]
Fixed.
