### ISSUE TITLE
Functionality Bug(Group-2): Employees and Guests with the Same Name Treated as the Same Entity

### ISSUE THREAD

**Issue by dkshjn** [IITGN-CS431/project-cns#5]
# Functionality Bug(Group-2): Employees and Guests with the Same Name Treated as the Same Entity

# Description
According to the project specification, employees and guests can have the same name but should be treated as **separate entities.** However, as shown in the attached image, the system treats them as the same person. When attempting to add a log entry for an employee and then for a guest with the same name ("Fred"), the system returns an error stating, "Already on campus," when it should allow both entries since they represent different entities (an employee and a guest).

<img width="730" alt="Screenshot 2024-10-23 at 11 32 13 PM" src="https://github.com/user-attachments/assets/a8b758be-2b43-4f1d-9d31-920d9111d23f">

**Comment by naveeeeeeeeeen** [comment]
I have fixed this bug and Created a pull request.
Sample Output:- 
![Screenshot from 2024-10-24 11-51-40](https://github.com/user-attachments/assets/ad2b741f-f6f1-4984-b532-d002b6c90029)

**Comment by bichhawat** [comment]
Resolved
