### ISSUE TITLE
Functionality Bug (Group 8): Invalid Room number accepted.

### ISSUE THREAD

**Issue by naveeeeeeeeeen** [IITGN-CS431/project-cns#51]
**According to project specifications, room number greater than 1073741823 should not be allowed.**
![WhatsApp Image 2024-10-25 at 00 30 03](https://github.com/user-attachments/assets/966be2be-4783-4aa0-90ba-b5c4b6cd63bd)

**According to project specifications, negative room number should not be allowed.**
![WhatsApp Image 2024-10-25 at 00 20 12(1)](https://github.com/user-attachments/assets/afa545d5-ae53-480a-b75f-d278c2752356)

**According to project specifications, alphabetical room number should not be allowed.**
![WhatsApp Image 2024-10-25 at 00 20 12](https://github.com/user-attachments/assets/8aaeee73-1688-4392-ab8a-1b7077c4943e)

**Comment by Kishan-Ved** [comment]
Fixed
