### ISSUE TITLE
Functionality Issue(Group-8) Invalid Timestamp is accepted

### ISSUE THREAD

**Issue by Chess-shrutiDubey** [IITGN-CS431/project-cns#52]
****As we can see in the image, an invalid timestamp is accepted which is wrong**. Timestamp should be between 1<=Timestamp<=1,073,741,823** 
![WhatsApp Image 2024-10-25 at 12 30 06 AM](https://github.com/user-attachments/assets/1f949475-28ea-4f5e-846d-91d1880797d6)

**Comment by Kishan-Ved** [comment]
Fixed

**Comment by Kishan-Ved** [comment]
@bichhawat Invalid timestamp and invalid room are both related and have a very similar fix. Both are reported: https://github.com/IITGN-CS431/project-cns/issues/52 and https://github.com/IITGN-CS431/project-cns/issues/51

Will we be penalized for both?

**Comment by bichhawat** [comment]
If you can fix this within the deadline of 48 hours, we won't be penalizing anyway
