### ISSUE TITLE
Functionality Issue (Group -8) Batch file Command are not accepted

### ISSUE THREAD

**Issue by Chess-shrutiDubey** [IITGN-CS431/project-cns#53]
**Here the batch file command is not working as mentioned in the readme.md** 
![WhatsApp Image 2024-10-25 at 1 21 26 AM](https://github.com/user-attachments/assets/1d9030ce-79e0-47b2-8309-d5d3f91ea750)

**Comment by shubham-agrawal04** [comment]
This is not an issue. You need to specify the log file path relative to the build folder, and not just specify the name of the file.
Try 'logappend -B ../batches/batch1' 
This should work

**Comment by Chess-shrutiDubey** [comment]
Thank you. Checked. The batchfile command is working. Although there is still some mistake. As in the image, we can see line 5 is an invalid command "James tries to leave campus without leaving the room", It causes the server to stop and the next lines are not processed.'

**Comment by Chess-shrutiDubey** [comment]
![IMG-20241025-WA0014](https://github.com/user-attachments/assets/3c12c1d5-36cd-4852-992a-471e2018faf4)
Thank you. Checked. The batchfile command is working. Although there is still some mistake. As in the image, we can see line 5 is an invalid command "James tries to leave campus without leaving the room", It causes the server to stop and the next lines are not processed.'

**Comment by Kishan-Ved** [comment]
@Chess-shrutiDubey Errors in the batch file lead to shutdown of the server, this bug has already been reported here https://github.com/IITGN-CS431/project-cns/issues/55
