### ISSUE TITLE
Functionality Bug (Group-8): Server Aborted Due to Lengthy Employee Name and Batch Errors Causing Crashes

### ISSUE THREAD

**Issue by dkshjn** [IITGN-CS431/project-cns#55]
#  Functionality Bug (Group-8): Server Aborted Due to Lengthy Employee Name

## Description

A batch file was created where a valid command was issued with the employee name being of **length 1100 characters**, this should have been processed as a valid input. However, the server responded with the error ```libc++abi: terminating due to uncaught exception of type std::invalid_argument: invalid employee name``` and subsequently crashed with a segmentation fault.

The command in the batch file:

```
-T 3 -K secret -A -E AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA log1
```

**If there is a limit imposed on the length of the employee name, the server should have handled it gracefully by informing the client that the name is too lengthy instead of crashing the entire server.**

## Demonstration:
<img width="672" alt="Screenshot 2024-10-25 at 5 44 50 AM" src="https://github.com/user-attachments/assets/b8bad985-18c9-4167-9f5b-d4c705aa3ddd">

The first image shows the client sending the command for running the batch file. It displayed that it is reading the command but shortly after the server throws an exception and terminates unexpectedly.

<img width="446" alt="Screenshot 2024-10-25 at 5 44 21 AM" src="https://github.com/user-attachments/assets/613f4062-65e6-44c2-abcc-7750b7903b3e">

The second image illustrates how the server crashed upon receiving the invalid input, rather than handling the situation appropriately by issuing a clear error message. Ideally, the server should inform the user if the employee name exceeds the allowed length and prompt them to shorten it, instead of terminating unexpectedly.

Reported by: Daksh Jain(22110066)

**Comment by Kishan-Ved** [comment]
@dkshjn I believe any error in the batch file shuts down the server. Is that correct?

**Comment by Kishan-Ved** [comment]
Please change the issue's title to avoid more people reporting the same error

**Comment by dkshjn** [comment]
Sure, will do.

**Comment by Kishan-Ved** [comment]
Fixed.
