### ISSUE TITLE
Functionality Bug (Group-6): Person not getting appended into room

### ISSUE THREAD

**Issue by VenkatReddybathuni** [IITGN-CS431/project-cns#56]
# Description

Giving the following set of instructions through a batch file:

![image](https://github.com/user-attachments/assets/c15cd5ec-5a58-4f1a-b7a3-e110083f6e74)

Then reading the state of rooms:

![image](https://github.com/user-attachments/assets/f38c6361-19c4-4ca9-a160-2ad7ea2600b0)

Here John and James were entered into room "0" according to the commands but upon invoking logread command there is no sign of them entering into room "0"

The ideal output would have been

![image](https://github.com/user-attachments/assets/31e002ce-2086-4a32-8a42-46e71a00f14a)

**Comment by Pranjal4697** [comment]
we have fixed this issue.
![image](https://github.com/user-attachments/assets/464c9a47-fe80-4391-a7a2-8bd9de069e4f)
