### ISSUE TITLE
Functionality Bug (Group-6): Person state inconsistent after leaving campus

### ISSUE THREAD

**Issue by VenkatReddybathuni** [IITGN-CS431/project-cns#57]
## Description

Giving the following set of instructions through a batch file:

![image](https://github.com/user-attachments/assets/9e15af89-7c94-43f9-a342-fcf0bf1337d7)

and then reading the state of rooms:
![image](https://github.com/user-attachments/assets/c627ec6f-c401-47a4-97d0-d06832192ede)

This is wrong because when a person enters the campus from log2 then he is on campus. But he was again allowed to enter the campus through log1.

Ideally there should have been an error message when we try to enter using the second log.

And also when the third command is executed the person should leave the campus, which is not happening.

**Comment by Pranjal4697** [comment]
We have fixed this issue. Now the changes are reflected when a person leaves the campus.

![image](https://github.com/user-attachments/assets/d561d703-3c7e-4d04-a949-55716536aa5c)
