### ISSUE TITLE
Functionality Bug (Group-6): Employees and Guests with same name not allowed to enter.

### ISSUE THREAD

**Issue by naveeeeeeeeeen** [IITGN-CS431/project-cns#6]
![1](https://github.com/user-attachments/assets/5b058b02-30e6-4694-8f18-bdc0ff255117)
According to the project requirements, Employees and Guests can have same name but should be treated as separate entities.
Here Employee Alia is on campus and Guest Alia is not allowed to enter. 
Also Employee Alia is on campus but Guest Alia was allowed to enter room.

**Comment by choudharyNetram** [comment]
Bug resolved.

![Bug6](https://github.com/user-attachments/assets/6d21a3b7-728f-4e7f-8446-e25fa51f83e9)
