### ISSUE TITLE
Functionality Bug (Group 2) : Unexpected behaviour

### ISSUE THREAD

**Issue by Kishan-Ved** [IITGN-CS431/project-cns#62]
![image](https://github.com/user-attachments/assets/b65b649b-23cd-44dd-9831-76afdc1d0581)

Let's say I set the password as -L

So the next command should be valid and Bob should enter the campus (because -L is the password and not the leaving action)

**Comment by naveeeeeeeeeen** [comment]
**Bug is now resolved.**
![Screenshot from 2024-10-25 17-10-31](https://github.com/user-attachments/assets/9415c047-e573-4a39-a5c8-fefa765bc8d2)

PR no. #73
