### ISSUE TITLE
Functionality Bug (Group 2) : Unexpected behaviour 2

### ISSUE THREAD

**Issue by Kishan-Ved** [IITGN-CS431/project-cns#63]
![image](https://github.com/user-attachments/assets/12d633f5-571a-43e2-ac18-19aff4db69eb)

Your code allows the user to create a log file named -L. This file however can't be accessed.

In line 2, -L is the file name and not the leaving action.

**Comment by Kishan-Ved** [comment]
This problem arises because you have made a separate command ./setup.py to allow the user to set the password and the filename, and also printed "setup done". Hence, in the next command, the user expects the availability of the log file named -L.

**Comment by Kishan-Ved** [comment]
@bichhawat Sir though the #61 and #62 look similar, they are actually different. Fixing one doesn't fix the other.

**Comment by Kishan-Ved** [comment]
@bichhawat Sir though the https://github.com/IITGN-CS431/project-cns/issues/63 and https://github.com/IITGN-CS431/project-cns/issues/62 look similar, they are actually different. Fixing one doesn't fix the other.

**Comment by bichhawat** [comment]
Sorry, marked as bug

**Comment by naveeeeeeeeeen** [comment]
**Resolved**
PR no. #73
