### ISSUE TITLE
Security Issue: Group 9

### ISSUE THREAD

**Issue by aayush8991** [IITGN-CS431/project-cns#67]
All account details and passwords are stored in bank.auth file without encryption. So, a user can access account details of anyone.
See the attached photos for reference.
![image](https://github.com/user-attachments/assets/98ab233f-e022-4d82-998c-fb8664cae2be)
![image](https://github.com/user-attachments/assets/f721c018-a221-4788-b3eb-230e3ca87614)
The passwords of account_1, account_2 and account_3 are available to everyone who uses the atm.

**Comment by bichhawat** [comment]
The bank.auth is on the server-side, right? If you can access this data using the atm program, then it could be a bug

**Comment by bichhawat** [comment]
As the group members have referenced this, it looks like this was a bug.
