### ISSUE TITLE
Authentication Issue: Group 9

### ISSUE THREAD

**Issue by aayush8991** [IITGN-CS431/project-cns#69]
The bank.auth file contains account name and passwords in unecrypted manner.
![image](https://github.com/user-attachments/assets/783bbc6e-10e7-4852-9f40-9cbc875518f1)

bank.auth should contain secret key to authenticate atm. Hence, there is no authentication of atm.

**Comment by bichhawat** [comment]
Can you add a minimum working example to show that an atm can access this data without the auth file, if I understand your issue correctly?

**Comment by bichhawat** [comment]
Referenced in PR, so may have been a bug
