### ISSUE TITLE
Functionality Bug(Group-8): Out-of-Range Exception Causing Server Crash for logappend and logread Commands

### ISSUE THREAD

**Issue by dkshjn** [IITGN-CS431/project-cns#71]
# Functionality Bug(Group-8): Out-of-Range Exception Causing Server Crash for logappend and logread Commands

## Description

When the command ```logappend``` or ```logread``` is issued without the required arguments, the server fails to handle the incomplete input, resulting in a crash due to an unhandled exception of type ```std::out_of_range: basic_string```. Instead of prompting an error such as ```invalid format``` or providing feedback for the missing arguments, the server abruptly shuts down.

This issue occurs because the logappend and logread parsing functions assume that certain flags (-T, -K, -E, etc.) and their corresponding arguments will always be provided. When no flags or arguments are given, as in the case where only logappend is sent, the program attempts to process the input and access non-existent arguments, leading to an std::out_of_range exception.

## Demonstration
The first image shows the server running on localhost, waiting for client connections. Upon receiving the incomplete command, the server encounters an out-of-range exception and crashes.
<img width="793" alt="Screenshot 2024-10-25 at 3 21 09 PM" src="https://github.com/user-attachments/assets/08c130fb-9b77-4f62-bf41-9821438ff6b4">

The second and third images show the incomplete logappend and logread commands being sent, triggering the server crash.
<img width="799" alt="Screenshot 2024-10-25 at 3 20 59 PM" src="https://github.com/user-attachments/assets/9c9c1209-03cb-441f-b204-f63e2054f9ae">
<img width="805" alt="Screenshot 2024-10-25 at 3 30 45 PM" src="https://github.com/user-attachments/assets/d6aeb869-e0ac-4162-bdfa-72930c1ade6f">
Ideally, the server should have responded with an "invalid format" error, as it does in other cases when the format or required arguments are missing.

Reported by: Daksh Jain (22110066)

**Comment by Kishan-Ved** [comment]
Fixed.
