### ISSUE TITLE
Functionality issue - Group 9 - Bank program shuts down when it shouldn't

### ISSUE THREAD

**Issue by Jiya-desai** [IITGN-CS431/project-cns#76]
In the specifications for the bank-atm security model, it has been mentioned that the bank server program should not stop running unless it explicitly receives an exit (SIGTERM signal or any other corresponding message) signal:

![spec](https://github.com/user-attachments/assets/c3bee8bb-0bcb-4b17-a9ec-39b166e299fe)

But in group 9's model, an invalid input from the client causes the bank program to shut down (check the last command - I entered a valid account name with an invalid card file for an operation):

ATM:
![ss1](https://github.com/user-attachments/assets/e2b48ae5-2b0b-44ad-9bba-6cfb1677fec6)

Corresponding bank:
![ss2](https://github.com/user-attachments/assets/e5da6d71-93a3-4b0b-9aa5-40e863a7eebf)

As can be seen, if a user accidentally/purposefully enters the wrong card file for an operation, the bank program closes, which shouldn't happen accordingly to the model requirements.

**Comment by ushasree-3** [comment]
#103 #105
