### ISSUE TITLE
Functionality bug (Group-9): Currency amounts

### ISSUE THREAD

**Issue by nishishah05** [IITGN-CS431/project-cns#77]
One of the functionalities asks for the following: Balances and currency amounts are specified as a number indicating a whole amount and a fractional input separated by a period. The fractional input is in decimal and is always two digits.
In case this is not satisfied, the following should occur: Any command-line input that is not valid according to the rules below should result with a return value of 255 from the invoked program and nothing should be output to stdout.
However, upon inputting a balance amount with 5 decimal places, no error is given and the bank successfully makes the card file. Although it clips the input, the required specification isn't satisfied.
ATM:
![Screenshot 2024-10-25 185935](https://github.com/user-attachments/assets/8325d51a-feab-4647-91a6-f895ad989e6c)
Bank: 
![image](https://github.com/user-attachments/assets/8ca4f567-c425-43a1-8e54-8b9f4515b121)

**Comment by ushasree-3** [comment]
#103 #104
