### ISSUE TITLE
Username greater than 130 charcaters[group 9]

### ISSUE THREAD

**Issue by Pratham-Sharda** [IITGN-CS431/project-cns#79]
requirement: File names are restricted to underscores, hyphens, dots, digits, and lowercase alphabetical characters (each character should match /[_\-\.0-9a-z]/). File names are to be between 1 and 127 characters long. The special file names "." and ".." are not allowed.

![error 9](https://github.com/user-attachments/assets/645c8761-65e6-491f-867d-5396ea6a68d6)

this is 130 chars long

**Comment by ushasree-3** [comment]
#103 #104
