### ISSUE TITLE
Functionality Bug (Group-6): Batch file processing produces incorrect log state.

### ISSUE THREAD

**Issue by naveeeeeeeeeen** [IITGN-CS431/project-cns#8]
![4](https://github.com/user-attachments/assets/f5e7e6ae-0115-437b-912e-d8dd1507149d)
Batchfile processing output shows ‘invalid’ but status shows entries have been added.
Status of ‘Guest James’ is shown wrong. He  should be in room no. 0.
Only line no. 5 should give ‘invalid’ as James tried to leave campus without leaving room no. 0.

**Comment by bichhawat** [comment]
Has this been fixed?

**Comment by Pranjal4697** [comment]
We have fixed this issue.
![image](https://github.com/user-attachments/assets/a77c20c5-1628-481c-9244-69214ef40769)
