### ISSUE TITLE
GROUP 5 - Compilation error

### ISSUE THREAD

**Issue by lavanya2504** [IITGN-CS431/project-cns#85]
During compilation, the following error is being shown. There are no steps mentioned in the readme file on how to set up the text file db_config
![image](https://github.com/user-attachments/assets/ff349e26-e056-4a11-ad47-cecacdb42323)
.

**Comment by AshStorm17** [comment]
db_config is needed to setup the MySQL database. 
We will include it in the Readme, however the file is really simple and can be easily found on the internet.

**Comment by bichhawat** [comment]
Please check if this works, if not we will reopen and mark it as bug.
