### ISSUE TITLE
Functionality Bug (Group 12) : Long names lead to faults

### ISSUE THREAD

**Issue by Kishan-Ved** [IITGN-CS431/project-cns#87]
![image](https://github.com/user-attachments/assets/15924913-4b39-4e9e-ba05-be6de228096e)

The client side gets the message : `successfully executed` even for the command with a very long name. However, we see that the server has reported some error, due to which that log entry has not been made in the logfile log 909.

**Comment by chakrie1489** [comment]
Fixed.
