### ISSUE TITLE
Functionality Bug (Group 10): Core dumped when no timestamp is entered

### ISSUE THREAD

**Issue by Kishan-Ved** [IITGN-CS431/project-cns#88]
![image](https://github.com/user-attachments/assets/a1f6d55b-dcbd-44c7-8018-db355f50334e)

Ideally, there should be an error message. However, the core gets dumped.

**Comment by rovin99** [comment]
Bug Fix #88 #111
<img width="525" alt="Screenshot 2024-10-26 at 5 28 39 PM" src="https://github.com/user-attachments/assets/7bfc95cb-2dd0-4665-95f8-9b51a78906b2">
