### ISSUE TITLE
Functionality Bugs (Group-10): Inconsistency issues.

### ISSUE THREAD

**Issue by naveeeeeeeeeen** [IITGN-CS431/project-cns#9]
1.) Alice left campus without exiting the room no. 10.
According to project specifications, no employee or guest should be allowed to leave the campus without leaving the room first.
![5](https://github.com/user-attachments/assets/edf37fd0-c5de-4692-9227-9219d5a375fe)

2.) Both -E and -G flags are allowed together.
![6](https://github.com/user-attachments/assets/8bee5f30-925b-488f-9c34-135ab6c9af48)

3.) Both -L and -A flags are allowed together.
![7](https://github.com/user-attachments/assets/f5d83328-dbbf-4e4f-9998-765901d89a06)

4.) Output is in Incorrect order. Fred entered and left room#1, then entered and left room#2, then entered and left room#3 and at last entered room#1.
![8](https://github.com/user-attachments/assets/e1ae76b5-a332-4467-bba5-9aa22ed40f1d)

**Comment by rovin99** [comment]
1. Now someone cannot leave campus while still being in a room.
<img width="551" alt="Screenshot 2024-10-25 at 12 29 51 AM" src="https://github.com/user-attachments/assets/b30a7031-ecfa-4d5b-9f19-0d20099c54e1">
2. -E and -G flags not allowed together.
<img width="584" alt="Screenshot 2024-10-25 at 12 41 19 AM" src="https://github.com/user-attachments/assets/eeedacc8-f8ad-4c2d-97fc-12de37ed9b65">
3. -L and -A flags are  not allowed together.
<img width="526" alt="Screenshot 2024-10-25 at 12 45 02 AM" src="https://github.com/user-attachments/assets/cd1cc23b-f789-43aa-bb6e-425425279744">
4.Room History now in order.
<img width="559" alt="Screenshot 2024-10-25 at 1 26 34 AM" src="https://github.com/user-attachments/assets/9f7b7f7b-343d-4d20-8c2d-47d115bf0cd3">

**Comment by bichhawat** [comment]
Has this been fixed? Please provide the PR number.

**Comment by rovin99** [comment]
> Has this been fixed? Please provide the PR number.

Yes. PR [e2076cc](https://github.com/IITGN-CS431/project-cns/pull/43/commits/e2076cc0e7b576dca433fc683550fa22e0328285)
