### ISSUE TITLE
Functionality Issue - Group 11 - Hardcoding of IP Address and Port Number

### ISSUE THREAD

**Issue by aayush8991** [IITGN-CS431/project-cns#90]
The IP Address and Port Number have been hard coded. Hence, the connection between two devices cannot be established unless the source code is changed.
![image](https://github.com/user-attachments/assets/f702230b-9002-4199-971e-453652631b9e)
![image](https://github.com/user-attachments/assets/bcdbb46f-e31a-4e55-b71b-021d6b480e5d)
There is no change in IP Address through the interface.

**Comment by arpan004** [comment]
Since both the client and server are running on the same device, there’s no need to change the IP address.

**Comment by aayush8991** [comment]
The main purpose of this project was to communicate between atm and bank (which is hosted on a server and not on the same device). In you client program, we cannot change the IP address unless changing the source code. You should take input of the IP address from the command line.
