### ISSUE TITLE
Bank Crashes on Closing ATM [Group 11]

### ISSUE THREAD

**Issue by AshStorm17** [IITGN-CS431/project-cns#94]
![{347AFC90-7B76-49D9-A0AD-246851BFB81F}](https://github.com/user-attachments/assets/0ba57804-ea9b-4801-baf6-95b148c6e6eb)

I ran the server.

![{319F9064-2FC3-4064-80E2-B44AB2E6FDF3}](https://github.com/user-attachments/assets/86262654-41a6-4101-a900-83d37533d9da)

Next I run a client to communicate with the server and kill it.

![{CEB3590D-C1CA-4960-A958-6C6359D93F68}](https://github.com/user-attachments/assets/e4a941dc-b3d6-4eb2-b4b6-c6e0b098638e)

I see that the bank crashed with Response: <No message here> as soon as the atm was killed.

**Comment by bichhawat** [comment]
Functionality bug
