### ISSUE TITLE
SECURITY BUG (GROUP 4): All the Log files & tokens are accessible in mongoDB

### ISSUE THREAD

**Issue by naveeeeeeeeeen** [IITGN-CS431/project-cns#96]
![Screenshot from 2024-10-26 00-34-02](https://github.com/user-attachments/assets/8a474fe5-5d04-46c9-be15-68cddd65b151)
![Screenshot from 2024-10-26 00-33-24](https://github.com/user-attachments/assets/6833338e-66ec-4eb9-82c5-f808edffba2c)
**Critical security vulnerability within MongoDB implementation that exposes sensitive logs and security tokens. 
This could lead to unauthorized access and data breaches.
No encryption used, Entries present in the database as Plaintext.**

**Comment by dkshjn** [comment]
It’s important to clarify that in this implementation, the server and database are designed to act as a single connected component. From what I understand, the approach you’ve followed here is to access the database directly from the server container without utilizing the client-side constructs. The key distinction is that you’ve run the queries directly against the database, bypassing the client-side entirely.

In such a setup, this would not qualify as a security bug in the traditional sense—particularly, this is not an instance of SQL injection, which occurs when untrusted input is manipulated to affect the execution of database commands from the client side. SQL injection or similar attacks would indeed be a critical vulnerability if performed from an untrusted external input source, such as the client.

However, what you’re doing here is more akin to internal system access, where you are directly querying the database from the server side. As discussed with @pratyush3757 Pratyush sir, in cases like this where the server and database are part of a secure, isolated environment, we do not treat this as a bug. It’s standard practice for the server and database, as interconnected components, to be treated as trusted components within this secured system.

In a scenario like this, unless there is unauthorized access from an external client or malicious input that compromises the server’s interaction with the database, this setup does not violate security principles by itself.

Diagram for reference:

Only the ports connected to client are exposed and not the internal server database.

![image](https://github.com/user-attachments/assets/c9d83134-f6af-46c7-88fa-553ad5f97b47)

**Comment by bichhawat** [comment]
This is okay in a client-server model. If the logs are on the client-side, they should not be readable without logappend, logread and the token
