### ISSUE TITLE
FUNCTIONALITY ISSUE (GROUP-04) Wrongly leaving of room without even entering

### ISSUE THREAD

**Issue by Chess-shrutiDubey** [IITGN-CS431/project-cns#99]
**Here Shahid and Salman can leave the room without entering it first which is wrong.**

![WhatsApp Image 2024-10-26 at 12 51 18 AM](https://github.com/user-attachments/assets/02c9f42d-ebcf-498f-a33f-3942a3bad20c)

**Comment by bichhawat** [comment]
What is the expected output?

**Comment by bichhawat** [comment]
I am going to close this as you have already reported the max. limit
